silx-kit/pyFAI

scripts/pyFAI-saxs

There is a typo in the varable name for number of points when calling integrate1d from the pyFAI-saxs script.

typo in varable name

---

pyFAI-src/calibration.py

pyFAI-recalib just dies with the error message. This is a patch to fix it.

Avoid "Namespace" error message for pyFAI-recalib

---

pyFAI-src/calibration.py

-p parameter was taken for pixel size, -P for polarization. Thus, -i became for poni, but then:
argparse.ArgumentError: argument -i/--poni: conflicting option string(s): --poni
This commit fixes this bug.

This fixes a regression due to fixed #194. See commit description

---

pyFAI-src/calibration.py

This is meant to improve the start point for refinement in pyFAI-calib.
initgeoRef - fills in default values as was done in the refine method (hopefully)
Then there are three "attempts". The first method is the one which was previously there (but inside initgeoRef). The second is that method plus geoRef.guess_poni. The third reads a poni file which happens to be in the current working directory (seems risky?). The best one is then chosen.
Testcases are still missing (use npt files ??)
Fixes #197

Better guesses for start of calibration refinement

---

.gitignore
run_tests.py

- Avoid generateing the log files for default tests
- Ignore the file in other cases

Avoid to generate profile.log default tests (improve #283)

---

setup.py

- data_files is still used for a win32 dll
- close issue #360

Remove resources from data_files (now we use package_data)

---

setup.py

Relative to https://github.com/silx-kit/pyFAI/issues/367.
But if numpy.distutils is really needed, that's only a workaround.

Fix setuptool extension

---

ci/appveyor.yml

- It is not possible to use setuptools version >23 and <25.1.4 to compile the project with Python 3.5 on Windows
- setuptools 25.1.4 was patched and is now released

Clean up compatibility code for setuptools (do not merge)

---

pyFAI/utils/shell.py

The trailing bar was not cleaned up  due to a wrong location of "\r"

Fix shell progressbar

---

setup.py

- setuptools 25.3.0 was patched
- numpy 1.11.2 was patched (not yet released)
- only few intersections between them are not working

Back to use extension from numpy (close #367)

---

make_man

- The inconvenient is it uses hard coded path
- But this script is not often used
Well. I think it is convenient. Cause i would like, at the end to remove all auto-generated content.
But i understand it is not merged, cause it is not portable.

Convenient PATH fix to generate man files from local project and not from installed scripts

---

version.py

Reveled when using `./bootstrap.py ./version.py` from make_man
No idea why it was not spotted before.

Fix global on RELEASE_LEVEL_VALUE

---

ci/appveyor.yml

The last version of setuptools is not working with appveyor + python 3.5.

Force setuptools version to 27.1.2

---

copyright
setup.py

This is the ides 
```
Jeromes-MacBook-Pro:pyFAI kieffer$ python setup.py --no-cython
OpenMP is not supported on Apple computers for OSX newer than 10.8
No Cython requested by command line
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: no commands supplied
Jeromes-MacBook-Pro:pyFAI kieffer$ python setup.py            
OpenMP is not supported on Apple computers for OSX newer than 10.8
OpenMP is not used. Cython files have to be re-generated
Compiling pyFAI/ext/_geometry.pyx because it changed.
[1/1] Cythonizing pyFAI/ext/_geometry.pyx
Compiling pyFAI/ext/reconstruct.pyx because it changed.
[1/1] Cythonizing pyFAI/ext/reconstruct.pyx
Compiling pyFAI/ext/splitPixel.pyx …
```

close #475

---

.landscape.yml

It ignores some paths with landscape, then the metric should be more interesting.
I mostly skip sandbox files and plugins files. We can talk about that.

Ignore some paths with landslides

---

.travis.yml
doc/source/changelog.rst
pyFAI/massif.py
pyFAI/peak_picker.py
scripts/eiger-mask
setup.cfg
version.py

Backport critical bug fix from 0.14-dev
- Convert matplotlib mouse input into pixel coordinates (fix issue with numpy 0.12)
- Fix eiger-mask script if h5py is not installed
- Use "/usr/bin/env python" for scripts

Backport from 0.14-dev to 0.13

---

setup.py

I only comment h5py dependency.
Here it work. It improve #576 but it do not fix the real problem.

Fast fix to be able to launch pyFAI scripts on Debian 8

---

pyFAI/calibration.py

`previous` variable was previously tested against `chi2_wavelength()`. It makes sense to initialize it with the same function.

Fix residual in case of free wavelength

---

pyFAI/app/integrate.py
pyFAI/average.py
pyFAI/geometry.py
pyFAI/io.py
pyFAI/test/test_all.py
pyFAI/test/test_integrate_app.py
pyFAI/worker.py

- It added tests for for pyFAI-integrate
- Therefore there is fix here and there for python, and buggy code
- It uses the monitor to fix the normalization factor: `normalization_factor = monitor`. Maybe it is `1/monitor`? I do it fast
- The normalization was stored on the result
- You can use this kind of param `--monitor-name=counter/mon`
- I do not update the GUI. We can provide a text input. But i presume it will not be a nice solution.
Closes #446

pyFAI-Integrate with monitor

---

build-deb7.sh

The `setup.py` was cleaned-up. `--no-cython` is an argument of the build target

Fix build-deb7

---

pyFAI/gui/calibration/ExperimentTask.py

This code was introduced while we was doing the release, to debug an issue on Windows. Unfortunately it was merged. See https://github.com/silx-kit/pyFAI/commit/c15cdf6680a55e0d8d4c300cc3e72cf48dad1b0e
It avoid to load any image from the GUI and replace the result by a random array of 10x10 pixels.

Clean up debug code

---

pyFAI/geometry.py
pyFAI/test/test_bug_regression.py
pyFAI/test/test_geometry.py

This provides a way to retrieve the rotation matrix from a geometry at the python level.
@jonwright could you review the patch ?

Provide the rotation matrix as example in geometry

---

run_tests.py

Few changes based on the state of silx.
Mostly:
- Option `-v` displays buffers in info mode
- Option `-vv` displays buffers in debug mode
- Remove option `-n` (juste use `-v` instead)

Update run tests

---

pyFAI/gui/jupyter.py

This PR fix the `matplotlib` import on Python2.
On the same package an own `matplotlib.py` exists.
Feed back from Pierre-Olivier Autran from ID22
```
ImportErrorTraceback (most recent call last)
<ipython-input-4-778183f83bd1> in <module>()
1 import pyFAI
----> 2 from pyFAI.gui import jupyter
3 from pyFAI.calibrant import get_calibrant
/usr/lib/python2.7/dist-packages/pyFAI/gui/jupyter.py in <module>()
42 import numpy
43 from pylab import subplots, legend
---> 44 from matplotlib import lines
45 
46 
ImportError: cannot import name lines
```

Fix matplotlib import on Python2

---

pyFAI/utils/shell.py

This case should only occur in unittest. And trying to reach the original `sys.stdout.encoding` in this case is a nightmare. As result our unittests do not test the real code which will be executed by the application. No luck for us.
Relative to #738

Use the safer aproch in case of non explicit encoding

---

pyFAI/gui/jupyter.py

It have to be defined before the module docstring.
Tested using the inplainting notebook on Python2

Fix absolute_import on Python 2

---

pyFAI/detectors.py
pyFAI/gui/calibration/DetectorSelector.py
pyFAI/gui/calibration/ExperimentTask.py
pyFAI/resources/gui/calibration-experiment.ui

- Fix binning with Rayonix detectors (calling 2 time `guess_binning` set the same detector state)
- Rework `guess_binning` to return True on success
- Rework pyFAI-calib2 to display max size of detector, binning, and if image and detector looks consistent. This can avoid some problems
- Display detector size of the experiment settings (this can be easily compared with the loaded image)
Closes  #760
Closes #762
Closes #763 
Closes #764

[calib2] Improve detector/image consistency

---

ci/requirements_rtd.txt

This is WIP but need to be merged to trigger build from RTD.
RTD is moving to python 3.5 as environment for building the doc

fix read the docs

---

pyproject.toml

The new pip supports toml files. This PR fix typo on the file which avoid to compile the project.
Closes #824

Fix typo on toml file

---

pyFAI/gui/cli_calibration.py

CheckCalib.img should be a Numpy array, not a fabio.edfimage.EdfImage instance

'CheckCalib.__init__' not setting the 'img' attribute correctly

---

pyFAI/app/calib2.py
pyFAI/detectors/_common.py
pyFAI/resources/gui/calibration-experiment.ui

There was a missing case in `guess_binning`.
I can't really manage all the cases as it is not very clear to me why for example we couldn't use a shape smaller than max_size in this case. Maybe it is cause of the splinefile?
Closes #851

[calib2] Fix "wrong size" with Frelon detector

---

.gitignore
pyFAI/ext/_distortion.pyx
pyFAI/ext/setup.py
pyFAI/ext/sparse_builder.pxi
pyFAI/ext/sparse_builder.pyx
pyFAI/test/test_all.py
pyFAI/test/test_sparse_builder.py

This PR introduce a `SparceBuilder` to simplify part of the cython code.
This could speed up CSR and LUT matrix by generating them in a single pass.
A default image 4096x4096 is stored in 377ms and exported as CSR in 1.63s. But there is still way to improve the current code.
```
In [27]: class Test(object):
...: 
...:     def __init__(self):
...:         import numpy
...:         self.shape = (4096, 4096)
...:         self.npt = 500
...:         y, x = numpy.ogrid[:self.shape[0], :self.shape[1]]
...:         self.tth = numpy.sqrt(x * x + y * y)
...:         self.maxI = 1000
...:         self.mod = 0.5 + 0.5 * numpy.cos(self.tth / 12) + 0.25 * numpy.cos(self.tth / 6) + 0.1 * numpy.cos(self.tth / 4)
...:         self.data = (numpy.ones(self.shape) * self.maxI * self.mod).astype("uint16") …
```

Sparse builder

---

pyFAI/azimuthalIntegrator.py
pyFAI/test/test_azimuthal_integrator.py

A legacy code on the Python azimuthal integrator engine was able to deal automatically with masking value `=1` or `=0`. This feature was based on data of the mask, considering it should contain less masked pixels than non-masking pixels and inverting the data if it was not the case.
Here is the code
```
if mask.sum(dtype=int) > mask.size // 2:
numpy.logical_not(mask, mask)
```
It is a legacy code, but:
- This feature is only active for the Python engine
- Then it is not consistent with other engine (and could introduce inconsistencies if we switch from one to another)
- On some rare cases the user expect to mask more pixels than available pixels
- It is kind of magic
We decide to remove this feature and make it simpler.
This PR introduce:
- A deprecation warning in case the feature is …

Deprecate legacy way of computing the mask

---

pyFAI/geometry.py

The error was:
```
In [7]: ai=pyFAI.load('18Aug29D5_0066.poni')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-3da680aacbdd> in <module>()
----> 1 ai=pyFAI.load('18Aug29D5_0066.poni')
/usr/lib/python2.7/dist-packages/pyFAI/__init__.pyc in load(filename)
82     """
83     from .azimuthalIntegrator import AzimuthalIntegrator
---> 84     return AzimuthalIntegrator.sload(filename)
85 
86 
/usr/lib/python2.7/dist-packages/pyFAI/geometry.pyc in sload(cls, filename)
1138         """
1139         inst = cls()
-> 1140         inst.load(filename)
1141         return inst
1142 
/usr/lib/python2.7/dist-packages/pyFAI/geometry.pyc in load(self, filename)
1173                 pixel1 …
```

close #903

---

pyFAI/test/test_utils.py
run_tests.py

small PR for better test coverage. No files remain unloaded (hence a low coverage)

fix the test coverage part in order to release v0.16

---

pyFAI/gui/utils/validators.py

Allow to move the dot by typing it anywhere, anyway a dot already exists
Could be merged to the release 0.16
Closes #943

Improve real number typing

---

pyFAI/gui/calibration/DetectorSelectorDrop.py
pyFAI/gui/calibration/ExperimentTask.py
pyFAI/gui/calibration/GeometryTask.py
pyFAI/gui/calibration/MaskTask.py
pyFAI/gui/calibration/PeakPickingTask.py
pyFAI/gui/calibration/RingCalibration.py
pyFAI/gui/calibration/RingExtractor.py
pyFAI/gui/calibration/helper/SynchronizeRawView.py
pyFAI/gui/calibration/model/GeometryConstraintsModel.py
pyFAI/gui/calibration/model/PlotViewModel.py
pyFAI/gui/utils/FilterBuilder.py
pyFAI/gui/widgets/CalibrantSelector.py
pyFAI/resources/gui/calibration-peakpicking.ui
pyFAI/resources/gui/constraint-drop.ui

- Allow to extract peaks using the fitted geometry (combo box to select the behaviour)
- Fix refitting now take care of the constraints (i.e. rot3 fixed to 0 remains at 0 after the refit)
- Sync the view of all the plots in order to see exactly the same pixels of the image at the same place of the screen (there is still a blink frame, but we can't do much with the current silx implementation)
- Sync config of all the plots (y-orientation, aspect ratio, interactive mode)
- Fix issue with constraints range not ordered (min>max)
- Add a slider for the range constraint
- Fix empty initialization of the detector selector
- Fix extensions displayed in most file dialogs
Closes #969 
Closes #996 
Closes #1006 
Closes #981 
Closes #990

Fixes few usability problems

---

pyFAI/gui/calibration/ExperimentTask.py

Improve the way no detectors is hilighted.
It could be done in a better way, but that's the simple way to avoid misunderstanding.
Closes #1016

Rework the way "no detector" is hilighted

---

pyFAI/gui/calibration/RingCalibration.py

The first guess from the peak was not using `guess_poni`.
Now it was fixed as it is done in the peak extraction.
Returning the better of 2 passes with and without `guess_poni`.

Fix guess poni

---

pyFAI/geometry.py

A simple fix for attempting to deepcopy while simultaneously integrating in multi-threaded use case.

Prevent size change during iteration

---

bootstrap.py
pyFAI/diffmap.py
pyFAI/gui/diffmap_widget.py

This PR mostly use the standard API to check if there is available semaphore (but also contains convenient fixes).
But i don't take the logic behind, or it was already broken, cause it was already possible to open many time the "run" screen.

Fix semaphore api

---

pyFAI/azimuthalIntegrator.py
pyFAI/detectors/_common.py
pyFAI/gui/test/test_integrate_widget.py
pyFAI/gui/widgets/WorkerConfigurator.py
pyFAI/test/test_worker.py
pyFAI/worker.py

This PR
- deprecate list of filenames provided to detector and azimuthal integrator (it could stay as an easy way to set but not as getter)
- enforce list of string for dark/flat config.
The idea is to use this (json version 2)
```
flat_field: ["foo1.edf", "foo2.edf", "foo3.edf"]
```
instead of this (json version 1)
```
flat_field: "foo1.edf,foo2.edf,foo3.edf"
```
Not tested

Deprecated comma list file

---

pyFAI/azimuthalIntegrator.py
pyFAI/geometry.py
pyFAI/gui/IntegrationDialog.py
pyFAI/gui/widgets/WorkerConfigurator.py
pyFAI/io/integration_config.py
pyFAI/io/ponifile.py
pyFAI/test/test_all.py
pyFAI/test/test_integrate_config.py
pyFAI/test/test_worker.py
pyFAI/worker.py

This isolate io for file config into the `io` package. It remove duplicated code and provide a safer compatibility with older config version (while dict are mess).
- Isolate `ponifile`read/write (we could do more: ideally `get/set_config` from azimuthalInteg should not contain `version`, as version should only be part of the storage -> the file)
- helper for integration-config (the json file).

Rework file config io

---

pyFAI/gui/dialog/Detector3dDialog.py

The loading was freezing, and we get this error : 
`ERROR:pyFAI.gui.dialog.Detector3dDialog:incompatible shape for a non-contiguous array`
Now it works with this change.

Fixed the 3D preview of CirPad detector.

---

pyFAI/ext/regrid_common.pxi

shouldd fix nightly build on edna-site

Typo preventing build on debian8 (numpy 1.8)

---

pyFAI/gui/dialog/Detector3dDialog.py

Use the coming-soon silx `ColormapMesh` to speed up the computation of the 3D shapes.
The result is about 2s with the Aarhus detector, which is much incredibly better. Previously it was about 2m or more.
It's only available with a not yet merged branch of silx.

Speed up 3D initialization

---

pyFAI/azimuthalIntegrator.py
pyFAI/opencl/__init__.py
pyFAI/opencl/test/__init__.py
pyFAI/test/test_preproc.py

`run_tests --no-opencl` was not anymore working
Maybe since silx opencl integration?

Fix tests with --no-opencl

---

pyFAI/app/average.py
pyFAI/app/calib2.py
pyFAI/app/integrate.py
pyFAI/gui/ApplicationContext.py
pyFAI/gui/model/AbstractModel.py
pyFAI/gui/model/ExperimentSettingsModel.py
pyFAI/gui/model/ImageModel.py
pyFAI/gui/tasks/ExperimentTask.py
pyFAI/gui/tasks/MaskTask.py
pyFAI/gui/widgets/FileEdit.py
pyFAI/gui/widgets/LoadImageToolButton.py
pyFAI/gui/widgets/MonitorNameEdit.py
pyFAI/gui/widgets/WorkerConfigurator.py
pyFAI/io/__init__.py
pyFAI/io/image.py
pyFAI/resources/gui/calibration-experiment.ui
pyFAI/resources/gui/worker-configurator.ui
pyFAI/test/__init__.py
pyFAI/test/test_all.py
pyFAI/test/test_io_image.py
pyFAI/test/test_worker.py
pyFAI/worker.py

This PR allow to have a full HDF5 workflow from acquisition to integration.
- Support HDF5 path on integrate
- Support fabio URLs `h5::dataset`
- Support silx URLs
- Support HDF5 path on integrate-gui
- Support silx URLs
- Support fabio URLs `h5::dataset`
- Allow to DnD mask/dark/flat from silx view
- Allow to load mask/dark/flat using HDF5 dialog
- Allow to DnD the monitor name
- Support HDF5 path on calib2
- Support silx URLs
- Support fabio URLs `h5::dataset`
- Allow to DnD mask from silx view
- Allow to load mask using HDF5 dialog
- Support HDF5 path on average
- Support fabio URLs `h5::dataset`
I try to do it from ID22 data (from P. O. Autran)
- HDF5/Nexus file from acquisition from calibant (`LaB6_60keV_380_tfout_1.h5`)
- HDF5/Nexus from acquisition from sample (`H76238.h5`)
- Plus …

HDF5 path compliant

---

setup.py

This PR synchronizes the setup.py with the current one from silx.
In particular:
- `sdist` now build the cythonized files
- The `numpy` version is was compiled with is advertise as a minimum required version
- `cython` is no more in setup_requires (we could argue about that...)

Synchronize setup.py with that of silx

---

MANIFEST.in

This PR adds `*.cpp` to `MANIFEST.in` as it was missing while there is some C++ extensions in `pyFAI.ext`.

Add *.cpp to manifest

---

pyFAI/ext/_histogram_nomp.pyx
pyFAI/ext/_histogram_omp.pyx
pyFAI/ext/_openmp.pxd
pyFAI/ext/histogram.py
pyFAI/ext/histogram.pyx
pyFAI/ext/setup.py
pyFAI/ext/src/openmp.h
setup.py

This PR proposes to move the choice of which implementation of the histogram to use from cythonization phase to C compilation phase.
To do so, both implementations of the histogram are built as separated Cython extensions (using stubs for OpenMP if it is not available).
The choice of implementation in the `histogram` module is done at runtime depending whether it was built with or without OpenMP.
There is a breach there as on can build the `_histogram*` modules without OpenMP and then the `histogram` module with OpenMP.... This can be (and should be) prevented, by checking if the `_histogram_omp` module was built with OpenMP. The `histogram` module can then be a pure Python module. If you are interested I can update this PR for it.
This looks to work, but requires more testing... Don't …

An alternative approach to OpenMP support in histogram

---

doc/source/geometry.rst
doc/source/geometry_conversion.rst
doc/source/geometry_conversion.tex
doc/source/pyFAI.rst
pyFAI/geometry.py
sandbox/dump_memcache.py

This is basically the document provided by Carsten to explain how he built the translator from ImageD11 to pyFAI and vice-versa. The document has been translated by pandoc from latex and typos have been manually fixed in the RST.

1189 doc geometry

---

pyFAI/app/benchmark.py
pyFAI/benchmark/__init__.py
pyFAI/method_registry.py
pyFAI/resources/openCL/ocl_azim_CSR.cl

* The benchmark tool was ending in error when no display was available
* The OpenCL code was still using the *pown* function, not available on certain platforms
* The benchmarking tool has been simplified, removing the LUT implementation as it is not of prime importance
* There has been a bug in the OpenCL device selection since the introduction of the registry. Now the benchmarking tool prints out the actual used device, not only the one it wish to use.

A couple of small error fixed:

---

pyFAI/gui/widgets/LoadImageToolButton.py

This PR makes `pyFAI-calib2` works with `PyQt5` from debian 8 (i.e., v5.3.2).
Feel free to reject if you don't want to support debian 8 (as Debian does).

Fix pyFAI-calib2 for debian8

---

README.rst
binder/index.ipynb
binder/postBuild
binder/requirements.txt

This PR adds a binder environment description to run pyFAI cookbooks and tutorials in Binder and a myBinder badge in the README to start it.
As it is, it installs the latest release, but uses notebooks from the tip of the project.
From what I tested, it mostly works, but some notebooks fail, I guess due to the 2GB RAM max limit on myBinder.
The PR can be tested here: https://mybinder.org/v2/gh/t20100/pyFAI/binder?filepath=binder%2Findex.ipynb

Add binder environment to run cookbook and tutorials

---

pyFAI/app/drawmask.py
pyFAI/geometry.py
pyFAI/gui/test/test_calibration.py
pyFAI/gui/test/test_integrate_widget.py
pyFAI/gui/test/test_model.py
pyFAI/gui/widgets/CalibrantPreview.py
pyFAI/opencl/azim_csr.py
pyFAI/opencl/ocl_hist_pixelsplit.py
pyFAI/opencl/preproc.py
pyFAI/opencl/sort.py
pyFAI/test/test_bug_regression.py
pyFAI/test/test_detector.py
pyFAI/test/test_preproc.py
pyFAI/units.py
pyFAI/utils/mathutil.py

- Fix calibrant widget preview
- From dead code compatibility for old silx
- Fix Qt tests using TestCaseQt
- Fix the auto import module to skip modules according to test options
- Also skip test modules as default, cause it is a nightmare
- Fix some opencl test to be able to import it without pyopencl
I think it would be better to disable the auto import module. It enforce import check which should not be needed. A log with un-imported modules could be enough to create test module for them.
Closes #1254

Fix run tests

---

pyFAI/io/__init__.py

Fixes h5py warning when loading h5 detector
Relative to  #1243

Uses [()] instead of deprecated .value

---

pyFAI/gui/helper/RingCalibration.py
pyFAI/gui/tasks/GeometryTask.py

Previous refactoring allow to use marching squares in a better way.
This PR move the marching squares from the fitting processing to the GUI.
As result we can only compute rings which are requested by the GUI, instead of computing everything.
This speed up each steps of the geometry fitting per 2 when using a very big image.

Do not compute all the ring polygons but only expected ones

---

pyFAI/detectors/_imxpad.py

Hello there,
To deal with the work on the cirpad detector, we need a new class wich is a vertical ImXPadS70 in pyFAI.
In fact it represents well one of our 20 modules of the Cirpad detector thus, it could helps us a lot if you actually merge it into pyFAI for the next release.
Thanks in advance,
Alexandre Marie

Added an ImXPadS70 in vertical shape

---

pyFAI/gui/helper/RingCalibration.py

I did not test it.
I only test the piece of code using ipython (Python3)
Relative to #1281

[calib2] Only use the first element to sort fits

---

pyFAI/gui/cli_calibration.py

'Massif' object has no attribute 'setValleySize'
It seems that this method has been removed from the Massif class, so this PR sets the value of valley_size directly to avoid an AttributeError.

AttributeError when calling AbstractCalibration.preprocess()

---

pyFAI/goniometer.py

Sometimes, the extraction of peaks from an image gives lot's of wrong
control points. We observe this phenomena when we have lot's of big
crystals (non continuous rings). This parameter allows the user to
solve this issue, by tuning the Imax expected for a real peak.

Added Imin in the extract_cp method.

---

pyFAI/test/test_geometry.py

use time.perf_counter on all platforms

fix appveyor on py3.8

---

pyFAI/utils/__init__.py

Fixes issue #1344 by changing normalizing relative path into an absolution path.

Fix path bug when packaging with PyInstaller

---

pyFAI/method_registry.py

The rational: json de-serialisation creates lists. here we need tuples
for immutability.

Enforce target to be a tuple

---

.travis.yml
ci/requirements_rtd.txt
ci/requirements_travis.txt

Select elder version of pytools when using python 3.5
As this is for CI, I did not open an issue.

Specify some version number for supporting python 3.5

---

pyproject.toml

Fixes https://github.com/silx-kit/pyFAI/issues/1537 by using https://github.com/scipy/oldest-supported-numpy as build dependency.
I am suggesting this bugfix but I didn't check if this is fully working - I don't have easy access to a windows system with a development environment setup.

Fix numpy build dependency 

---

setup.py

`doubleword` is needed by the OpenCL part of pyFAI

bump version of silx

---

pyFAI/utils/orderedset.py

collections.MutableSet was deprecated a long time ago and removed with python3.10.
https://docs.python.org/3/whatsnew/3.10.html#removed
https://bugs.python.org/issue37324
Using the old class name leads to test failures such as this one:
```
======================================================================
ERROR: test_import_all_modules (pyFAI.test.test_bug_regression.TestBugRegression)
Try to import every single module in the package
----------------------------------------------------------------------
Traceback (most recent call last):
File "/<<BUILDDIR>>/pyfai-0.20.0+dfsg1/.pybuild/cpython3_3.10_pyfai/build/pyFAI/test/test_bug_regression.py", line 286, in test_import_all_modules
raise err
File "/<<BUILDDIR>>/pyfai-0.20.0+dfsg1/.pybuild/cpython3_3.10_pyfai/build/pyFAI/test/test_bug_ …
```

Fix collections.MutableSets compat with python3.10

---

pyFAI/ext/splitBBox.pyx

The signatures of a number of functions were changed in #1528.  This restores
the ability to pass by keyword pos0Range and pos1Range in histoBBox1d adn
histoBBox2D.
If both the old and new parameters are passed, `ValueError` is raised, if only
the old keyword is passed a warning is issued.  If the value is passed
as a positional the users is unaware of this change.
-----
This was brought to my attention because it broke @gfreychet . 
If you want to rename a lot of keywords, it may be worth vendoring a version of a decorator we have in Matplotlib that handles all of the "only pass one" logic.

API: restore back compatibility in histoBBox1d and histoBBox2d

---

ci/requirements_rtd.txt
pyFAI/azimuthalIntegrator.py

Investigation on empty bins when performing sigma-clipping with Poisson error model

Avoid empty bins in sigma-clipping

---

pyFAI/resources/gui/calibration-experiment.ui
pyFAI/resources/gui/calibration-geometry.ui
pyFAI/resources/gui/calibration-mask.ui
pyFAI/resources/gui/calibration-peakpicking.ui
pyFAI/resources/gui/calibration-result.ui

Dear developers, 
I replaced the horizontal layout with panel splitting so that the right part can be stretched out (reducing the image size) in order to better accomodate the widgets. It's particularly useful in the geometry panel where the values of the PONIs and rotations are quite large (I was missing the 10**-9 exponent that was on the rightmost part of "rotation3"...)
here is a screenshot of the result (you can see the draggable dot in the middle between the two panels):
The diff is huge just because the ui gets scrambled out when removing the outermost layout (I used the qt-designer).
Thanks for this great software!

added splitters

---

pyFAI/test/test_csr.py
pyFAI/test/test_histogram.py
pyFAI/test/utilstest.py

These tests now fail all the time on armhf in Ubuntu, and I could pass lowmem to skip them I guess but it seems better to skip these tests by default and avoid losing the coverage of the other lowmem tests (which all seem to pass fine).

skip tests that are unreliable on 32-bit platforms by default

---

pyFAI/azimuthalIntegrator.py

cython integrator to prevent integrator reset.
replaces cbc99979e016f08f6dc8eeb71676a629597325be
close #1788 
close #1789

Copied integration ranges in integrate2d_ng opencl implementation from

---

pyFAI/resources/openCL/peakfinder.cl
pyFAI/resources/openCL/sparsify.cl

Hi!
By looking at the code, I have the impression that the `clamp`  invocations in the OpenCL code do not account for the correct upper  `DIM - 1` limit of the corresponding array indexes. If this is the case, they do not completely protect against buffer overflows.
What do you think? Is that correct?
Cheers

Fix upper limit in clamp OpenCL invocations to avoid buffer overflow

---

pyFAI/calibrant.py
pyFAI/detectors/_common.py
pyFAI/gui/model/CalibrantModel.py
pyFAI/gui/model/GeometryModel.py
pyFAI/gui/utils/unitutils.py
pyFAI/gui/widgets/CalibrantPreview.py
pyFAI/gui/widgets/CalibrantSelector.py
pyFAI/gui/widgets/DetectorLabel.py
pyFAI/gui/widgets/GeometryLabel.py
pyFAI/gui/widgets/MethodLabel.py
pyFAI/gui/widgets/OpenClDeviceLabel.py
pyFAI/utils/ellipse.py

This is a small PR with mostly fixes on doc and types, and small UI polish.
Feel free to tell me what you want to pick, i can create dedicated PR per commits if you prefer.
e78be61ad2d1421ff101900f4348ce5256f1875e is a commit that could in theory introduce a bug.
other commits are pretty safe.
During the years i have rework my tooltips on Flint.
The patches on `<ul><li>` make the result a bit more compact and readable.
The proposal on the calibrant selector make the resulut smaller.
It's a trick to force Qt to use a pure Qt component instead of a widget from the system (or i misunderstand).
Instead of

Some polish, doc, types

---

pyFAI/calibrant.py

This PR is a proposal to store the calibrant from pyFAI as a resource.
Plus some review of the code, documentation, typing.
Now a calibrant resource from pyfai is stored as `_filename = "pyfai:LaB6"`.
The file path is generated only when it have to be read.
This way it is easy to distinguish calibrant from resources, and other user calibrants.
If one try to change and save such calibrant, it raises an exception.

Rework pyFAI calibrant as resource

---

pyFAI/gui/CalibrationContext.py
pyFAI/gui/dialog/DetectorSelectorDialog.py
pyFAI/gui/tasks/ExperimentTask.py
pyFAI/gui/widgets/CalibrantSelector.py
pyFAI/gui/widgets/CalibrantSelector2.py
pyFAI/gui/widgets/DetectorSelector.py
pyFAI/gui/widgets/meson.build
pyFAI/gui/widgets/model/AllDetectorItemModel.py
pyFAI/gui/widgets/model/CalibrantFilterProxyModel.py
pyFAI/gui/widgets/model/CalibrantItemModel.py
pyFAI/gui/widgets/model/DetectorFilterProxyModel.py
pyFAI/gui/widgets/model/__init__.py
pyFAI/gui/widgets/model/meson.build
pyFAI/resources/gui/calibrant-selector2.ui
pyFAI/resources/gui/calibration-experiment.ui
pyFAI/resources/gui/meson.build

Here is a test to provide a new popup for the calibrant widget.
Related to #1902 
I wanted to speed up the user selection.
First I have tried to provide a minimalistic periodic table of elements to group the calibrants, but it is probably not very convenient to use.
So my guess here is to provide the recently used calibrants.
The code provides:
- A calibrant widget with diffrent selectors
- The last 8 recently used calibrants are displayed
- This also store/restore user calibrants load from files (so no need to search for a file twice)
- A button to load a calibrant from file

New calibrant widget

---

pyFAI/detectors/_hexagonal.py

when initializing 4D array for pixel coordinates
* in-place operation
* float32 instead of float64
* delete temporary buffers
related to #1912 
validated on i386 and 1GB memory

Lower the memory consumption

---

bootstrap.py
pyFAI/gui/widgets/CalibrantSelector2.py

This PR fixes #1931.
The user selection was not propagated to the `calibrantModel`.
+ A fix on the `bootstrap.py` to allow to execute entry-points

calib2: Fixes calibrant selection

---

doc/source/changelog.rst
doc/source/coverage.rst
version.py

- Bug fix release over 2023.08
- Fix calibrant selection in calib2 (Thanks Valentin)
- Centralized control of Random Number Generator for tests, to make non-regression test more consistent for CI.
- Correct behaviour of dynamic mask (was causing systematic crashes)
- Correct spelling of several messages.
- Compatibility with matplotlib 3.7
- New application icon and launcher under linux
- Updated notebook (addresses API changes)

pyFAI-2023.09

---

ci/requirements_appveyor.txt
ci/requirements_gh.txt
ci/requirements_travis.txt
pyproject.toml
requirements.txt
setup.py

Do you prefer this ?
How to ensure this gets propagated to debian/conda/ ... ?

Prevent the usage of the broken numexpr

---

pyFAI/gui/utils/unitutils.py

Here is an update of the helper convertor to handle tth_rad to d^-2.
It's a rework of the info from `pyFAI.units`, but i would be happy to have a double check here.
Could you please check if the math is right?
BTW: I also have that code in Flint for now, to be sure it is working with previous pyFAI versions.

Added convertion from tthrad to RecD2_NM

---

pyFAI/azimuthalIntegrator.py
pyFAI/engines/CSC_engine.py
pyFAI/engines/CSR_engine.py
pyFAI/ext/splitBBoxCSC.pyx
pyFAI/ext/splitBBoxCSR.pyx
pyFAI/ext/splitBBoxLUT.pyx
pyFAI/ext/splitPixelFullCSC.pyx
pyFAI/ext/splitPixelFullCSR.pyx
pyFAI/ext/splitPixelFullLUT.pyx
pyFAI/opencl/azim_csr.py
pyFAI/opencl/azim_hist.py
pyFAI/opencl/azim_lut.py

Fix improper reset 2d integrator

---

pyFAI/gui/utils/ProxyAction.py
pyFAI/test/test_calibrant.py

Fix tests for python 3.12

---

src/pyFAI/gui/dialog/Detector3dDialog.py

This was causing an issue when viewing calibration model in 3D - need to change numpy.float to just float due to deprecation of numpy.float

remove reference to numpy.float

---

src/pyFAI/gui/tasks/GeometryTask.py
src/pyFAI/io/ponifile.py

When clicking on the "saxs mode", the rotations are all set to zero and locked.
The consequence is that the beam-stop is moved to the PONI location which is usually worse than the guessed beam-stop. 
This PR changes the PONI to the former beam-stop position so that rings should not move when enforcing the SAXS mode. The subsequent fit should also be more reliable.
close #1992

Set the PONI to the beam-stop and not the opposite in SAXS mode.

---

src/pyFAI/_version.py
src/pyFAI/azimuthalIntegrator.py
src/pyFAI/detectors/_adsc.py
src/pyFAI/detectors/_common.py
src/pyFAI/detectors/_dectris.py
src/pyFAI/detectors/_esrf.py
src/pyFAI/detectors/_hexagonal.py
src/pyFAI/detectors/_imxpad.py
src/pyFAI/detectors/_non_flat.py
src/pyFAI/detectors/_others.py
src/pyFAI/detectors/_psi.py
src/pyFAI/detectors/_rayonix.py
src/pyFAI/detectors/_xspectrum.py
src/pyFAI/detectors/meson.build
src/pyFAI/detectors/orientation.py
src/pyFAI/geometry/core.py
src/pyFAI/geometryRefinement.py
src/pyFAI/test/test_detector.py
src/pyFAI/test/test_geometry.py

This is likely to be a beefy one ...
close #1994

Manage orientation of detector

---

doc/source/changelog.rst
src/pyFAI/detectors/orientation.py
src/pyFAI/geometry/core.py
src/pyFAI/gui/dialog/DetectorSelectorDialog.py
src/pyFAI/gui/model/DetectorModel.py
src/pyFAI/gui/tasks/ExperimentTask.py
src/pyFAI/gui/widgets/DetectorLabel.py
src/pyFAI/resources/gui/calibration-experiment.ui
src/pyFAI/resources/gui/detector-selection-drop.ui

Expose the orientation selection in the calibration GUI (v2)

---

src/pyFAI/app/benchmark.py
src/pyFAI/benchmark/__init__.py
src/pyFAI/method_registry.py

New attributes for "pyFAI-benchmark" tool (only 1d integration works fine so far)
New arguments for argument parser:
- Pixel splitting argument (-ps, --pixelsplit): no, bbox, pseudo, full, all (default=bbox)
- Algorithm argument: histogram (-algo, --algorithm), CSR, CSC, LUT, all (default=histogram, CSR)
- Implementation argument (-i, --impl): python, cython, opencl, all (default=cython, opencl)
- Function argument (-f, --function): legacy, ng, all (default=all)
- all argument (--all) (boolean): if True, benchmarks every available method (default=False)
- Not processor argument (--no-proc): if used, skips the benchmark using the central processor (useful if you want to benchmark only GPU devices using --gpu)
- Some changes in the figure legends to be consistent with the documentation of …

new arg parser for 1d

---

doc/source/changelog.rst
src/pyFAI/detectors/__init__.py
src/pyFAI/detectors/_adsc.py
src/pyFAI/detectors/_common.py
src/pyFAI/detectors/_hexagonal.py
src/pyFAI/io/ponifile.py
src/pyFAI/test/test_detector.py

Register the number of pixel corners

---

src/pyFAI/gui/widgets/LoadImageToolButton.py

Explicitely close the dialog to prevent crash

---

requirements.txt
src/pyFAI/meson.build
src/pyFAI/ring_extraction.py
src/pyFAI/test/meson.build
src/pyFAI/test/test_all.py
src/pyFAI/test/test_ring_extraction.py

resolves #2078 
This is my implementation of `extract_cp` as a RingExtraction class. The 2 main things I changed here were adding threading inside  `extract_control_points` which runs `extract_list_of_peaks_in_one_ring` concurrently; and `_get_unique_two_theta_values_in_image` which sets `two_theta_values` array to only go to the max two_theta_value encompassed in the calibration image.
As I was making this I did see that @kif created a PR already to speed things up using cython, but I thought I'd send in the PR anyway to see if we could combine them together, as I made a class for it as well. My idea was to make the class to separate the many things `extract_cp` was doing into smaller methods for clarity and making testing easier.
And speaking of tests, I'd like some help running with …

create RingExtraction class 

---

src/pyFAI/gui/diffmap_widget.py

Remove RuntimeError in the case of non-explicit declaration of npt_rad, using the GUI of diff_map

remove RuntimeError

---

src/pyFAI/diffmap.py

Now, diffmap works by using a config file generated by pyFAI-integrate, + adding manually the additional needed parameters (output_file, input_file slow_points, fast_points:
```
pyFAI-diffmap ../pilx_test/RAW_DATA/scan0001/eiger/eiger_0000.h5 --config ../pilx_test/config.json -o /tmp/kk.h5 -r 6 -t 6 --no-gui
```
Before, even if the integration parameters are all there, it was not using them. Now it loads the poni parameters, nbpt_rad and nbpt_azim into the config["ai"] dictionary, takes the mask parameter from the .json file and if the method contains opencl, it takes it (before that, it only goes opencl if it's explicitly typed in CLI)
Json file:
```
{
"application": "pyfai-integrate",
"version": 3,
"wavelength": 3.7380000000000004e-11,
"dist": 0.18352000680503333,
"poni1": …
```

additional possibilities in diffmap

---

src/pyFAI/diffmap.py
src/pyFAI/gui/pilx/MainWindow.py
src/pyFAI/gui/pilx/widgets/ImagePlotWidget.py
src/pyFAI/gui/pilx/widgets/MapPlotContextMenu.py
src/pyFAI/gui/pilx/widgets/MapPlotWidget.py
src/pyFAI/gui/pilx/widgets/meson.build

Now, single click plots multi-selection by default.
Double-click plots only one plot (substitutes all the time)
Thoughts about this approach? Single click should be one-plot and double-click multiselection?
Do not use double click at all?

2129 pilx multiselection , click / double-click approach

---

src/pyFAI/ext/splitPixelFullCSC.pyx
src/pyFAI/ext/splitpixel_common.pyx
src/pyFAI/test/test_bug_regression.py

full-split CSC matrix has wrong size when last line of detector is masked out

---

src/pyFAI/azimuthalIntegrator.py
src/pyFAI/engines/CSC_engine.py
src/pyFAI/engines/CSR_engine.py
src/pyFAI/engines/histogram_engine.py
src/pyFAI/engines/preproc.py
src/pyFAI/ext/LUT_common.pxi
src/pyFAI/ext/histogram.pyx
src/pyFAI/ext/preproc.pyx
src/pyFAI/ext/splitBBox.pyx
src/pyFAI/ext/splitPixel.pyx
src/pyFAI/method_registry.py
src/pyFAI/opencl/azim_hist.py
src/pyFAI/test/test_azimuthal_integrator.py

and remove the WIP tags laying around.

Implement unweighted average for 2D integration 

---

src/pyFAI/app/benchmark.py

Legacy is maybe faster but it provides incorrect results.
close #2173

Benchmark only the `ng` version on the integrator

---

src/pyFAI/io/spots.py

f = fabio.open(file.h5)
if f is a LimaImage instance from fabio, f.dataset is a h5py.dataset, so len(f.dataset) is the number of frames inside the dataset
But if f is an EigerImage instance, f.dataset is a list, (with 1 or more items):
```
In [22]: f = fabio.open('/data/scisoft/edgar/collect_01_00001_data_000001.h5')
In [23]: type(f)
Out[23]: fabio.eigerimage.EigerImage
In [24]: f.dataset
Out[24]: [<HDF5 dataset "data": shape (100, 2167, 2070), type "<u4">]
In [25]: len(f.dataset)
Out[25]: 1
In [26]: f = fabio.open('/data/scisoft/edgar/lysozyme_100T-lysozyme_100T0000.h5')
In [27]: type(f)
Out[27]: fabio.limaimage.LimaImage
In [28]: f.dataset
Out[28]: <HDF5 dataset "data": shape (1000, 2164, 2068), type "<i4">
In [29]: len(f.dataset)
Out[29]: 1000
```

transform one dataset to list

---

src/pyFAI/azimuthalIntegrator.py

This PR makes the `absorption` parameter usable from high-level functions `integrate1d_ng` and `sigmaclip_ng`. 
For `integrate1d_ng` there are lots of different class instantiations depending on the model/implementation/etc ; not sure all of them support the `absorption` parameter.
Also perhaps this parameter should be made visible to other functions.

Add "absorption" kwarg to integrate1d_ng and sigmaclip_ng

---

src/pyFAI/diffmap.py
src/pyFAI/gui/pilx/MainWindow.py
src/pyFAI/gui/pilx/widgets/DiffractionImagePlotWidget.py

[pilx] new features

---

src/pyFAI/gui/model/ExperimentSettingsModel.py
src/pyFAI/gui/tasks/IntegrationTask.py
src/pyFAI/resources/gui/calibration-result.ui

New feature at the end of pyFAI-calib2, to save an integration .json file together with the .poni file

[pyFAI-calib2] new feature: save .json file

---

src/pyFAI/average.py

Added option to save 4D data after reduction where the dimension is: N_frames x Channel x X_dim x Y_dim:
one file with 4D data,i.e., like NumPy format 
append frames to stack, i.e., like edf
create separate files for each channel, i.e., like  tif (Pilatus)

This pull request addresses issue #2221

---

src/pyFAI/azimuthalIntegrator.py

GIWAXS/fiber integration should be done without pixel splitting, to not fill any point within the missing wedge
```
from pyFAI.units import get_unit_fiber
import numpy as np
from pyFAI import load
from pyFAI.gui.jupyter import plot2d, plot1d
import  matplotlib.pyplot as plt
import time
qip = get_unit_fiber(name='qip_nm^-1') 
qoop = get_unit_fiber(name='qoop_nm^-1')
data = np.load('/data/scisoft/edgar/pyfai_files/data_eiger2m.npy')
poni = '/data/scisoft/edgar/pyfai_files/poni_eiger.poni'
ai = load(poni)
res2d = ai.integrate2d(data=data, npt_rad=1000, npt_azim=360, unit=(qip,qoop), method=("no", "csr", "cython"))
```
For a fiber integration, for example between qIP=[0,5] and qOOP=[0,30], this is the array to integrate (using split_pixel="no"):
```
res2d_limit = ai.integrate2d_ng(data=data, …
```

[GIWAXS] force split_pixel=no

---

src/pyFAI/gui/pilx/MainWindow.py
src/pyFAI/gui/pilx/widgets/DiffractionImagePlotWidget.py

Allow multiple sources for the dataset

---

src/pyFAI/app/drawmask.py
src/pyFAI/gui/CalibrationContext.py
src/pyFAI/gui/IntegrationDialog.py
src/pyFAI/gui/dialog/Detector3dDialog.py
src/pyFAI/gui/matplotlib.py
src/pyFAI/gui/pilx/widgets/DiffractionImagePlotWidget.py
src/pyFAI/gui/utils/colorutils.py

Common default colormap

---

src/pyFAI/azimuthalIntegrator.py

Straightforward methods to get the qip-qoop map, without explicit method without pixel splitting and without instantiating the units (same as integrate_grazing_incidence or integrate_fiber) but in 2D
Example:
```
res2d_gi = ai.integrate2d_grazing_incidence(data=data, npt_horizontal=1000, incident_angle=0.12*3.14/180, tilt_angle=0.0, sample_orientation=2)
```

integrate2d_fiber API

---

src/pyFAI/test/test_all.py
src/pyFAI/test/test_fiber_integrator.py

The number of tests increased from 433 to 450 (+2s runtime)

Include fiber integrator into test suite

---

src/pyFAI/integrator/fiber.py
src/pyFAI/test/test_fiber_integrator.py
src/pyFAI/units.py

Since the fiber unit contains parameters (incident_angle, tilt_angle and sample_orientation), there has to be more than one object

lighter FiberIntegrator class

---

src/pyFAI/opencl/test/test_collective.py
src/pyFAI/resources/openCL/collective/comb_sort.cl
src/pyFAI/resources/openCL/collective/reduction.cl

Test for OpenCL Comb-Sort

---

.pre-commit-config.yaml
doc/source/publications.rst
src/pyFAI/containers.py
src/pyFAI/engines/CSR_engine.py
src/pyFAI/ext/CSR_common.pxi
src/pyFAI/ext/meson.build
src/pyFAI/ext/sparse_utils.pyx
src/pyFAI/ext/splitPixelFullCSR.pyx
src/pyFAI/test/test_all.py
src/pyFAI/test/test_medfilt_engine.py

Review after #2334 is merged
close #2315

Cython implementation of medfilt_ng

---

src/pyFAI/integrator/fiber.py

More than 100 lines less in fiber integrator

simplify fiber integrator

---

doc/source/publications.rst
src/pyFAI/opencl/__init__.py
src/pyFAI/opencl/azim_csr.py
src/pyFAI/opencl/azim_hist.py
src/pyFAI/opencl/azim_lut.py
src/pyFAI/opencl/peak_finder.py
src/pyFAI/opencl/preproc.py
src/pyFAI/opencl/test/test_preproc.py
src/pyFAI/resources/openCL/preprocess.cl

Work aroung a bug in Apple Silicon GPU driver
Close #2339

[OCL] Explicitely disable fp64

---

src/pyFAI/io/image.py

Convert boolean mask array to int8

---

src/pyFAI/geometry/core.py
src/pyFAI/units.py

For two units called `scattering_angle_horz` and `scattering_angle_vert` ; the key to cache the arrays is the same for both units (`scattering`). 
Can we change it and use just the full unit.name?

Use unit.name as key cache

---

src/pyFAI/app/benchmark.py
src/pyFAI/app/calib.py
src/pyFAI/app/calib2.py
src/pyFAI/app/integrate.py
src/pyFAI/app/mx_calibrate.py
src/pyFAI/app/recalib.py

Remove debugging entry-point from applications

cybersecurity

---

src/pyFAI/integrator/azimuthal.py
src/pyFAI/test/test_azimuthal_integrator.py
src/pyFAI/utils/mathutil.py

equivalence azimuth and radial units

---

src/pyFAI/app/integrate.py
src/pyFAI/worker.py

Auto guess the binning from the reading of the first image

---

src/pyFAI/geometry/core.py
src/pyFAI/test/test_geometry.py

Normalize azimuthal range

---

src/pyFAI/gui/pilx/MainWindow.py

This allows to hide the intense gaps in Eiger images thus better auto- color scale.
close #2432

[pilx] use dynamic masking for diffraction images

---

src/pyFAI/multi_geometry.py

Trying to combine two detectors with different pixel dimensions, I got an error like this:
```text
File /gpfs/exfel/sw/software/mambaforge/22.11/envs/202501/lib/python3.11/site-packages/pyFAI/multi_geometry.py:169, in MultiGeometry.integrate1d(self, lst_data, npt, correctSolidAngle, lst_variance, error_model, polarization_factor, normalization_factor, lst_mask, lst_flat, method)
167 variance = None
168 if self.radial_range is None:
--> 169     self.radial_range = self._guess_radial_range()
170 if self.azimuth_range is None:
171     self.azimuth_range = self._guess_azimuth_range()
File /gpfs/exfel/sw/software/mambaforge/22.11/envs/202501/lib/python3.11/site-packages/pyFAI/multi_geometry.py:113, in MultiGeometry._guess_radial_range(self)
111 def _guess_radial_range(self):
112 …
```

Allow MultiGeometry to guess radial & azimuthal ranges when detectors are different shapes

---

src/pyFAI/detectors/_xspectrum.py

The module positionning is probably adapted detector by detector, not simple to assess the mask automatically.
Use dynamic mask => dummy value.
close #2447

Declare shape of the Lambda9M detector.

---

src/pyFAI/integrator/azimuthal.py
src/pyFAI/test/test_azimuthal_integrator.py

@picca this is related to your email on the 
Fri, 28 Feb 2025 14:02:51 +0100 (CET)
Could you re-run the faulty test with this patch ? thanks.
```
======================================================================
ERROR: test_medfilt1d (pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon.test_medfilt1d)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 290, in test_medfilt1d
ocl = self.ai.medfilt1d_ng(self.data, N, method=("no", "csr", "opencl"), **param)
File "/usr/lib/python3/dist-packages/pyFAI/integrator/azimuthal.py", line 1578, in medfilt1d_ng
raise RuntimeError("Not yet implemented. Sorry")
RuntimeError: Not yet implemented. Sorry …
```

Provide a more explicit exception

---

src/pyFAI/detectors/_common.py
src/pyFAI/ext/CSR_common.pxi
src/pyFAI/integrator/azimuthal.py
src/pyFAI/test/test_azimuthal_integrator.py
src/pyFAI/test/test_csr.py
src/pyFAI/test/test_geometry.py
src/pyFAI/test/test_integrate.py
src/pyFAI/test/test_mask.py
src/pyFAI/test/test_utils_mathutil.py

Needs to adapt certain tests ...
close #2466

automatic dynamic mask for Dectris detetors

---

README.rst
ci/requirements_appveyor.txt
doc/source/operations/index.rst
doc/source/project.rst
package/debian13/control
package/debian13/py3dist-overrides
pyproject.toml
requirements.txt
run_tests.py
src/pyFAI/gui/matplotlib.py

was PyQt5, but Qt5 is left unmaintained.

Migrate Qt backend to PySide6 by default

---

src/pyFAI/app/saxs.py
src/pyFAI/app/waxs.py
src/pyFAI/benchmark/__init__.py
src/pyFAI/gui/CalibrationContext.py
src/pyFAI/gui/cli_calibration.py
src/pyFAI/gui/diffmap_widget.py
src/pyFAI/gui/tasks/MaskTask.py

Use `fabio.fabioutils.exists()` instead of `os.path.exists()` to accept '::' seprated HDF5 dataset descriptors
close #308

Replace `os.path.exists()`

---

src/pyFAI/app/average.py

A beamline called me with an issue which was actually a typo in the argument and they did not understand from the stdout
```bash
pyFAI-average /path/to/file.h5
WARNING:pyFAI.app.average:No input file specified.
```

improve pyFAI-average warning

---

src/pyFAI/crystallography/space_groups.py

This PR is a work in progress for adding reflection support as discussed in [#2555](https://github.com/silx-kit/pyFAI/issues/2555).
Feedback is welcome during development. I’ll mark as “Ready for review” when it's finished.

[Crystallography] Extinction rules for differents space groups
