silx-kit/pyFAI

- pyFAI-src/utils.py
This is useful for summing up short exposure images from counting detectors. Only tested it with edf files created by our machinee, maybe also useful for others?
> Added averaging method "add"

- pyFAI-src/diffmap_widget.py
- pyFAI-src/gui_utils.py
- third_party/copyright
- third_party/pyside_dynamic.py
For diffmap_widget, there is still an issue with PySide having a different return value for QtGui.QFileDialog.getOpenFileNames: 2-tuple (file_list, filter) instead of file_list for PyQt4.
> Update PySide uic.loadUi

- doc/build/_sources/biblio.txt
- doc/build/_sources/pyFAI.txt
- doc/build/_sources/usage/cookbook/calibrate.txt
- doc/build/_sources/usage/cookbook/integration_with_python.txt
- doc/build/_sources/usage/cookbook/integration_with_scripts.txt
- doc/source/biblio.rst
- doc/source/conf.py
- doc/source/design/ai.rst
- doc/source/detector.rst
- doc/source/man/detector2nexus.rst
- doc/source/man/diff_map.rst
- doc/source/man/diff_tomo.rst
- doc/source/man/pyFAI-calib.rst
- doc/source/operations/windows.rst
- doc/source/pyFAI.rst
- doc/source/usage/cookbook/calibrate.rst
- doc/source/usage/cookbook/integration_with_python.rst
- doc/source/usage/cookbook/integration_with_scripts.rst
- doc/source/usage/tutorial/Geometry/geometry.rst
- doc/source/usage/tutorial/Introduction/introduction.rst
- doc/source/usage/tutorial/MakeCalibrant/make_calibrant.rst
- doc/source/usage/tutorial/MultiGeometry/index.rst
- pyFAI/geometry.py
- setup.py
But the documentation still not contains program output, while there is no more exceptions in the build_doc logs
> Fix doc compilation (close #338)

- .travis.yml
- scripts/pyFAI-integrate
> related to #348

- doc/source/conf.py
> fix issue with debian packaging

- scripts/pyFAI-drawmask
The Silx API changed before the release of Silx 0.2.
This patch use the final one.
> Fix drawmask for silx 0.2

- ci/appveyor.yml
> Fix typo on appveyor yaml

- pyFAI/calibration.py
Few patches to support both Python 2 and 3
> Python 3 compatibility code (fix issue #368)

- pyFAI/azimuthalIntegrator.py
> Fix AzimuthalIntegrator.integrate2d when using filename param

- ci/appveyor.yml
Try to fix a recent issue on setuptool (i fail to reproduce it on our windows machine)
> Add cython at system test

- README.rst
- doc/source/project.rst
- package/debian/control
- pyFAI/test/test_utils.py
- pyFAI/utils/__init__.py
Implemnetation without python-fftw anymore.
close #220 #390
> Remove the dependency on python-fftw3: fall back on numpy

- pyFAI/detectors.py
waiting for some test data ...
> fix the Xpad_flat (3.2) detector geometry

- pyFAI/detectors.py
> fix the Xpad_flat geometry

- ci/appveyor.yml
- This PR should install setuptools 27.3.1
- If everything pass it can be merge (especially Windows Python 3.5)
> Back to use last setuptools

- copyright
- pyFAI/azimuthalIntegrator.py
- pyFAI/distortion.py
- pyFAI/ext/preproc.c
- pyFAI/ext/preproc.pyx
- pyFAI/worker.py
Start integrating preprocess (OpenMP-parallel, factorized) into:
* pixelwise worker
* distortion correction worker
* correct a bug in AzimuthalInegrator regarding normalization of data
> Common preproc

- pyFAI/gui_utils.py
- pyFAI/integrate_widget.py
Replaced by the default system browser
> Remove QtWebKit (close #448)

- setup.py
- Change the order of the check of openmp and cython (argument first, then environment)
- add --force-cythonize
- Force cythonize if OpenMP is not expected (assert that default cythonized files was generated with openmp (maybe we should change this?))
- Plus some clean up
> Fix openmp setup

- pyFAI/multi_geometry.py
> add mask and flat to MultiGeometry

- pyFAI/azimuthalIntegrator.py
- pyFAI/geometry.py
- pyFAI/test/test_worker.py
- pyFAI/worker.py
correct polarization -> polarization_factor
> Polarization id02

- pyFAI/test/test_geometry.py
> basically replacce a pilatus300k with a 100k

- pyFAI/detectors.py
Comes from the refinement (pyFAI-calib) of very precise data from ID15/31
> Close #523

- doc/source/calibration.rst
- doc/source/design/ai.rst
- doc/source/detector.rst
- doc/source/geometry.rst
- doc/source/glossary.rst
- doc/source/index.rst
> Attempt for a glossary with many links to existing documentation.

- doc/build/_sources/api/pyFAI.txt
- doc/source/api/pyFAI.rst
- doc/source/design/ai.rst
- pyFAI/calibration.py
- pyFAI/ext/_bispev.pyx
- pyFAI/ext/bilinear.pxi
- pyFAI/ext/bilinear.pyx
- pyFAI/ext/relabel.pyx
- pyFAI/opencl.py
> Typo in ai doc

- pyFAI/units.py
monotonically growing, it is defined all over R -> R
It is an interesting function to complement or even replace log for 
the color interpretation
close #525
> Unless log, arcsinh is a well behaved function:

- pyFAI/test/test_scripts.py
- pyFAI/test/utilstest.py
Relative to #535
Few fixes, and improvement in case of not so clean env.
> Fix script search on Windows

- pyFAI/calibration.py
- pyFAI/ext/preproc.pyx
> 558 assign

- pyFAI/benchmark/setup.py
- pyFAI/ext/setup.py
- pyFAI/ext/src/crc32.c
- pyFAI/gui/setup.py
- pyFAI/resources/setup.py
- pyFAI/setup.py
- pyFAI/third_party/setup.py
- pyFAI/utils/setup.py
- setup.py
- Uses `setup.py` from `silx`
- There is still part of custom code
> Update setup.py with silx one

- README.rst
> Add conda to readme

- pyFAI/app/calib2.py
- pyFAI/gui/calibration/ExperimentTask.py
- pyFAI/gui/calibration/GeometryTask.py
- pyFAI/gui/calibration/IntegrationTask.py
- pyFAI/gui/calibration/MaskTask.py
- pyFAI/gui/calibration/PeakPickingTask.py
- pyFAI/gui/calibration/RingExtractor.py
- pyFAI/gui/calibration/model/ExperimentSettingsModel.py
Small things, but quite useful. Tested with real acquisition images.
> Small fixes on the GUI prototype

- pyFAI/gui/calibration/GeometryTask.py
- pyFAI/gui/calibration/PeakPickingTask.py
- pyFAI/gui/calibration/model/CalibrationModel.py
- pyFAI/gui/calibration/model/GeometryModel.py
- More stable behaviours for reset and fit buttons
> Improve calib2

- pyFAI/gui/calibration/GeometryTask.py
- pyFAI/gui/calibration/QuantityEdit.py
- pyFAI/gui/calibration/validators.py
> Fix double validator

- pyFAI/goniometer.py
> Address the bug when parameter names are provided but only 1 parameter actually varies

- pyFAI/test/test_preproc.py
> Try to fix: those tests run >4000 times without failure

- pyFAI/multi_geometry.py
close a couple of issues on multi-geometry
> 538 multigeometry

- pyFAI/app/drawmask.py
> Fix vmin/vmax to avoid silx issue

- .gitignore
> Clean up git ignore

- pyFAI/app/average.py
- pyFAI/app/calib.py
- pyFAI/app/calib2.py
- pyFAI/app/detector2nexus.py
- pyFAI/app/diff_map.py
- pyFAI/app/diff_tomo.py
- pyFAI/app/drawmask.py
- pyFAI/app/eiger_mask.py
- pyFAI/app/integrate.py
- pyFAI/app/recalib.py
- pyFAI/app/saxs.py
- pyFAI/app/waxs.py
> Capture warnings from warning module as logging warnings

- doc/source/api/pyFAI.rst
- Fix module name
Relative to #642
> Fix documentation

- ci/amd_sdk.sh
- See https://github.com/silx-kit/silx/pull/1030/commits/b9ecb4494c5cbc0e5d2e734390c521e438dc44fe
> Fix AMD OCL SDL

- .gitignore
- MANIFEST.in
> exclude Jupyter notebooks checkpoints.

- setup.py
> Add silx as an install dependancy

- doc/source/changelog.rst
- setup.cfg
- version.py
> Backport 0.14.1

- pyFAI/app/drawmask.py
- pyFAI/diffmap_widget.py
- pyFAI/integrate_widget.py
Only the following applications are impacted:
- drawmask
- integrate
- diff_map
> Fix Qt static dialog to be compatible with Qt5

- pyFAI/opencl/test/test_addition.py
- pyFAI/test/test_azimuthal_integrator.py
- pyFAI/test/test_csr.py
- pyFAI/test/test_flat.py
- pyFAI/test/test_integrate.py
- pyFAI/test/test_mask.py
- pyFAI/test/test_ocl_sort.py
- pyFAI/test/test_openCL.py
- pyFAI/test/test_preproc.py
- pyFAI/test/utilstest.py
- run_tests.py
- Can be done by run_tests.py --no-opencl
- Or using envvar PYFAI_OPENCL=False
Closes #667
> Skip OpenCL if requested

- version.py
provide a citation as part of the library
> Provide a default citation for the software

- pyFAI/test/test_bug_regression.py
Fix script location of the regression tests
Closes #641
> Fix regression test

- pyFAI/azimuthalIntegrator.py
- pyFAI/decorators.py
- pyFAI/test/test_geometry.py
- Clean up test logs
- Fix uses of deprecated functions done by pyFAI itself
- There is still 48 deprecation warnings from tests (too much to fix them for now)
> Fix deprecation warnings

- MANIFEST.in
- pyFAI/opencl/common.py
Issue with debian packaging, manifest and OpenCL
> second attempt for 0.14.2

- pyFAI/gui/calibration/model/WavelengthToEnergyAdaptor.py
- pyFAI/units.py
Use the one defined in `pyFAI.units`
> Fix universal constants

- pyFAI/gui/calibration/IntegrationTask.py
> [calib2] Use the fitted wavelength to save the poni file

- ci/appveyor.yml
- pyFAI/distortion.py
test using scipy v1.0 beta instead of the one provided by wheelhouse of silx
> scipy 1.0 beta

- pyFAI/detectors.py
- pyFAI/geometryRefinement.py
- pyFAI/goniometer.py
This PR allows to fit the wavelength in a goniometer definition function.
It resolves also a long lasting bug when the wavelength was increasing and the number of rings was shrinking. This PR should limit the effect.
> Gonio wavelength

- pyFAI/gui/jupyter.py
> Fix jupyter rendering

- pyFAI/goniometer.py
> close #710

- build-deb.sh
- package/debian8/control
- package/debian9/control
- pyFAI/opencl/processing.py
- setup.py
> Packaging ubuntu

- pyFAI/azimuthalIntegrator.py
- pyFAI/opencl/processing.py
- pyFAI/test/test_azimuthal_integrator.py
> 715 azimuthal variance

- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/processing.py
Allows to process data from a pyopencl.array
> From opencl

- pyFAI/average.py
- setup.py
> 719 many frames

- pyFAI/multi_geometry.py
close #723
change threshold for saxs data
> Bug in multi_geometry for SAXS data

- pyFAI/geometry.py
- pyFAI/test/test_geometry.py
> 725 calcfrom2d

- pyFAI/gui/calibration/PeakPickingTask.py
> Fix ring number for input/output to npt

- pyFAI/diffmap.py
- pyFAI/ext/splitBBoxLUT.c
- pyFAI/ext/splitBBoxLUT.pyx
Looks to be set but never used
> Clean up output_dummy

- pyFAI/gui/calibration/IntegrationTask.py
- Add an alpha channel to have a better rendering
> Tune marker color

- doc/source/conf.py
> fix for read the docs

- ci/amd_sdk.sh
> Fix AMD_SDK URL

- pyFAI/azimuthalIntegrator.py
- pyFAI/ext/inpainting.c
- pyFAI/ext/inpainting.pyx
According to the data, the image was fully masked, then no valid pixels was available.
This PR:
- Avoid infinite loop
- Provide a runtime exception explaining there is no valid pixels
Close #739
> Fix inpainting typo

- pyFAI/units.py
> Fix hc unit

- pyFAI/test/test_bug_regression.py
> non-regression test on hc constant

- pyFAI/test/test_bug_regression.py
- pyFAI/test/test_scripts.py
- pyFAI/test/utilstest.py
- run_tests.py
- By default do not log script output
- Displayed if the return code is non null
- Displayed if logging is in debug (use ./runtests -vv)
- In installation mode, the installed script is tested (use ./runtests --installed)
- In non-installation mode, the script from the module is executed
Closes #766
> Fix script tests

- version.py
> bump version 0.16 dev

- pyFAI/calibrant.py
- pyFAI/test/test_calibrant.py
- setup.py
close #775 
offer a selection of the precision in addition
> 775 calibrant

- pyFAI/app/integrate.py
- pyFAI/integrate_widget.py
- pyFAI/io.py
- pyFAI/test/test_azimuthal_integrator.py
- pyFAI/test/test_openCL.py
- pyFAI/test/test_peak_picking.py
- pyFAI/worker.py
Reported by Frederic from Python3 Debian build deb
Closes #780
> Clean up text file life cycle

- pyFAI/goniometer.py
Fred (@picca) & Erik from soleil will be happy
> close #801

- pyFAI/detectors/_others.py
- pyFAI/detectors/_rayonix.py
> Define a couple of MAR detectors

- pyFAI/__init__.py
- pyFAI/ext/_geometry.pyx
- pyFAI/geometry.py
- pyFAI/test/test_bug_regression.py
This time, we actually check the chi-array is properly discontinued at the proper place
close #816
> 816 bug hist2d

- pyFAI/ext/splitBBoxCSR.pyx
- pyFAI/geometry.py
- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/sort.py
- pyFAI/test/test_geometry.py
This generalized the usage of cached array for:
* the cosine of the incidence angle
* the solid_angle array
* the transmission correction array
The code is simpler and less error prone. 
Properties are providing compatibility with former API
> Generalize cached array

- pyFAI/geometry.py
compatibility with former code
> close #826

- .travis.yml
- ci/before_install-linux.sh
- ci/intel_opencl_icd.sh
- ci/requirements_travis.txt
- pyFAI/geometry.py
try to provide an alternative ICD
> 829 open cl travis

- pyFAI/spline.py
- pyFAI/test/test_spline.py
> Add test on spline flipping and coef calculation

- pyFAI/azimuthalIntegrator.py
something very simple, missing in new generation integrators
> unit in output

- pyFAI/opencl/processing.py
- pyFAI/opencl/sort.py
This is a simple correction for a couple of inconsistencies in the OpenCL part.
Used for benchmarking
> Ocl profile

- pyFAI/app/saxs.py
- pyFAI/app/waxs.py
- pyFAI/detectors/_common.py
This is an attempt to address #860
> close #860

- pyFAI/ext/regrid_common.pxi
> Use types comming from numpy to enforce the length

- pyFAI/ext/_distortion.pyx
- pyFAI/ext/sparse_builder.pxd
- pyFAI/ext/sparse_builder.pxi
- pyFAI/test/test_sparse_builder.py
> Implement to_lut to sparse builder

- pyFAI/detectors/_adsc.py
- pyFAI/detectors/_common.py
- pyFAI/detectors/_dectris.py
- pyFAI/detectors/_esrf.py
- pyFAI/detectors/_imxpad.py
- pyFAI/detectors/_others.py
- pyFAI/detectors/_rayonix.py
- pyFAI/geometry.py
- pyFAI/test/test_detector.py
- pyFAI/test/test_geometry.py
Maybe there is a need for a set_config for detector not compatible with default constructor...
> Provide detector configuration within the PONI file

- doc/source/publications.rst
> Fix author order in publication

- pyFAI/goniometer.py
- pyFAI/gui/cli_calibration.py
- Remove pyFAI isocontour from cli calibration
- Remove pyFAI isocontour from goniometer calibration
It have to be tested strongly. I don't try it.
BTW, using a non square image to test is useful to catch axes problems.
Relative to #881
> Remove isocontour from cli calib

- version.py
> Start beta phase

- pyFAI/gui/test/__init__.py
- pyFAI/gui/test/test_calibration.py
Test the GUI using an initialized GUI model.
There is no mouse interaction.
Closes #917
> Add naive tests

- pyFAI/gui/calibration/DetectorSelectorDrop.py
- pyFAI/gui/calibration/ExperimentTask.py
- pyFAI/gui/calibration/IntegrationTask.py
- pyFAI/gui/calibration/PeakPickingTask.py
- pyFAI/gui/utils/FilterBuilder.py
Clean up the way file dialog filters are generated.
Also fix filters for supported formats like `edf.gz`.
Closes #944
> Improve filedialog filters

- doc/source/man/pyFAI-calib2.rst
- doc/source/man/scripts.rst
- doc/source/usage/cookbook/calib-gui/index.rst
> Doc calib2

- pyFAI/__init__.py
- pyFAI/average.py
- Removes var from public api
- Removes var from the documentation
> Reduce scope of var

- pyFAI/gui/calibration/PeakPickingTask.py
- pyFAI/gui/calibration/helper/MarkerManager.py
- pyFAI/gui/calibration/model/PeakModel.py
- pyFAI/gui/calibration/model/PeakSelectionModel.py
- pyFAI/gui/utils/validators.py
- pyFAI/resources/gui/calibration-peakpicking.ui
- Merge all available action about peak picking in a single toolbar
- Clean up
- Fix few exception
This PR could be merge to the 0.16 branch as there is no big changes
Closes #964 
Closes #934
> Merge peakpicker actions

- pyFAI/gui/test/__init__.py
- pyFAI/gui/utils/setup.py
- pyFAI/gui/utils/test/__init__.py
- pyFAI/gui/utils/test/test_validators.py
- pyFAI/gui/utils/validators.py
> Fix validators

- pyFAI/detectors/_common.py
Provide a setter which properly sets the detector for saving ....
> 999 detector pixel corner distortion v2

- pyFAI/detectors/_common.py
- pyFAI/ext/bilinear.pyx
- pyFAI/geometry.py
geometry.save fixes also the datector name which is now "nexus" instead
of the alias
> fix issue with non-contiguous detector on cython

- pyFAI/detectors/_imxpad.py
Cached the computation of pixel corners in order to avoid multiple
computation.
> Fixed the Cirpad performance issue

- pyFAI/gui/calibration/CalibrationContext.py
- pyFAI/gui/calibration/ExperimentTask.py
- pyFAI/gui/calibration/GeometryTask.py
- pyFAI/gui/calibration/IntegrationTask.py
- pyFAI/gui/calibration/MaskTask.py
- pyFAI/gui/calibration/PeakPickingTask.py
- pyFAI/gui/calibration/helper/SynchronizeMaskToolColor.py
- pyFAI/gui/calibration/helper/SynchronizePlotBackground.py
- pyFAI/gui/calibration/model/ExperimentSettingsModel.py
- pyFAI/gui/calibration/model/MaskedImageModel.py
- pyFAI/gui/calibration/utils.py
- pyFAI/gui/utils/imageutils.py
- pyFAI/resources/gui/calibration-result.ui
- Hide the masked pixels image in the peaking and fitting task
- Allow to display integrated mask
- Rework the way style are managed
- Current colors are not the final ones
> Improve displayed mask

- pyFAI/ext/regrid_common.pxi
- pyFAI/ext/splitBBox.pyx
- pyFAI/ext/splitPixel.pyx
- pyFAI/test/test_split_pixel.py
First give it a try before cleaning up ...
> 1021 preproc inlined

- pyFAI/app/integrate.py
- The first frame was always used for the integration
> Use data from frame (not from the file)

- pyFAI/azimuthalIntegrator.py
- pyFAI/test/test_saxs.py
- pyFAI/utils/decorators.py
- version.py
Implement future deprecation warning, same as fabio
close #1035
> 1035 future deprec

- pyFAI/azimuthalIntegrator.py
- pyFAI/geometry.py
> Warn if the discontinuity is in the azimuthal range

- package/debian9/rules
Upgrade debian packaging to user Python3
> user Python3 for running pyFAI scripts

- pyFAI/gui/calibration/GeometryTask.py
Here is the current state. It's better, there is maybe still a bug somewhere
Closes #1055
> Ring displacment

- pyFAI/gui/widgets/QuantityEdit.py
> Fix linux copy-paste using middle mouse button

- pyFAI/gui/calibration/PeakPickingTask.py
- pyFAI/gui/calibration/model/AbstractModel.py
- pyFAI/gui/calibration/model/PeakSelectionModel.py
> Avoid move peaklist scrollbar

- pyFAI/gui/IntegrationDialog.py
> Fix edf integration

- pyFAI/gui/calibration/IntegrationTask.py
- pyFAI/gui/calibration/MaskTask.py
- pyFAI/gui/calibration/PeakPickingTask.py
- pyFAI/gui/calibration/model/ExperimentSettingsModel.py
- pyFAI/gui/calibration/model/ImageModel.py
- pyFAI/gui/calibration/model/MaskedImageModel.py
- Fix integration if there is no mask
- Use by default the detector mask
- Robustness here and there
Closes #1064
> Fix integration process

- pyFAI/gui/calibration/DetectorSelectorDrop.py
- pyFAI/gui/test/__init__.py
- pyFAI/gui/test/test_detector_dialog.py
- Fix weak detector definitions
- Add unittest
- Allow to double click to select a detector
Closes #1065
Closes #1068
> Fix custom detector

- pyFAI/gui/calibration/GeometryTask.py
> Implement default/saxs constraints push buttons

- pyFAI/gui/calibration/MaskTask.py
> Robustness on MaskTask

- setup.py
> Update silx version requirement

- pyFAI/test/test_goniometer.py
Tried to fix : Warning in tests #1091
> [warning] in tests

- version.py
> new version of PR#1122 ... incrementing the proper value

- pyFAI/azimuthalIntegrator.py
- pyFAI/method_registry.py
This offers a fast-path and an error correction
> No warnings

- pyFAI/io/__init__.py
One should never merge before the end of the tests
> fix regression

- pyFAI/gui/tasks/MaskTask.py
> Support silx 0.10 mask tool

- pyFAI/calibrant.py
> spotted when using dioptas

- pyFAI/resources/gui/calibration-experiment.ui
fixing a typo in the experiment gui
> typo fix in GUI

- setup.py
> close #1157

- pyFAI/app/average.py
- pyFAI/app/integrate.py
- pyFAI/average.py
- pyFAI/gui/IntegrationDialog.py
- pyFAI/gui/dialog/GeometryDialog.py
- pyFAI/gui/diffmap_widget.py
- pyFAI/gui/model/Fit2dGeometryModel.py
- pyFAI/gui/model/GeometryModel.py
- pyFAI/gui/test/test_integrate_widget.py
- pyFAI/gui/widgets/WorkerConfigurator.py
- pyFAI/io/__init__.py
- pyFAI/resources/gui/geometry-dialog.ui
- pyFAI/resources/gui/integration-dialog.ui
- pyFAI/spline.py
- pyFAI/test/test_all.py
- pyFAI/test/test_average.py
- pyFAI/test/test_integrate_app.py
- pyFAI/test/test_utils_header.py
- pyFAI/utils/header_utils.py
- pyFAI/utils/logging_utils.py
- pyFAI/utils/shell.py
- Support multiframe/fileseries/h5 as input
- Support h5 as output
- Support `h5::entrypath` as output
- Fix progress bar display (logging message are displayed over it)
- Support monitor from HDF5
- Statistics on processing
- Check resulting NXdata (1d integration + error and 2d integration are displayable with `silx view`)
- Fix problem of "hdf5 output already exists" (introduce command line options `--delete` (delete the file) `--overwrite` (overwrite the NXentry path)  `--append` (create a new NXentry)
- Integrating GUI allow allow to edit the geometry (the fid2d geometry is also editable)
- Integrating GUI uses now a scrollbar to allow to reduce the height of the window.
Closes #1142
Closes #1155
Closes #1156
Closes #1150
Closes #1145
Closes #1046
Closes #1145
Closes #1143 
Closes …
> Improve integrate

- pyFAI/detectors/_common.py
- pyFAI/test/test_detector.py
> Fix NexusDetector copy

- pyFAI/utils/header_utils.py
> Fix monitor for fabio 0.9 and erlier

- doc/source/api/pyFAI.rst
- pyFAI/ext/invert_geometry.pyx
Addresses the documentation part of #1208.
The performance issue on windows remains a mystery.
> Minimal documentation on invert_geometry

- pyFAI/resources/openCL/ocl_azim_CSR.cl
- pyFAI/resources/openCL/ocl_azim_LUT.cl
> Simplify the kernel for being able to run on PortableCL with PTX backend

- pyFAI/opencl/azim_hist.py
- pyFAI/resources/openCL/deactivate_atomic64.cl
which claims it supports 64-bits atomics but actually doesn't!
close #1219
> Provide an ugly workaround against AMD's compiler bug 

- pyFAI/ext/splitBBox.pyx
This option should probably be extended to all other rebinning engines but this a lot more of work.
@ronpandolfi, @gfreychet can you confirm it works for your use-case ?
close #1218
> This is workaround for issue #1218.

- pyFAI/app/calib2.py
- pyFAI/gui/CalibrationWindow.py
- pyFAI/gui/model/ExperimentSettingsModel.py
- pyFAI/gui/model/FilenameModel.py
- pyFAI/gui/tasks/IntegrationTask.py
This PR add a message dialog in case the PONI file was not saved.
This could save lives
Closes #1199
> Reminder to save PONI file

- pyFAI/gui/tasks/ExperimentTask.py
- pyFAI/gui/utils/test/test_validators.py
- pyFAI/gui/utils/validators.py
- pyFAI/gui/widgets/FitParamView.py
- pyFAI/gui/widgets/QuantityEdit.py
- pyFAI/gui/widgets/WorkerConfigurator.py
> Fix valid energy

- pyFAI/opencl/OCLFullSplit.py
> fix ImportError

- pyFAI/detectors/_common.py
> Fix deepcopy memo arg to NexusDetector

- pyFAI/gui/tasks/PeakPickingTask.py
> Fix rubber mode

- pyFAI/gui/helper/MarkerManager.py
- pyFAI/gui/tasks/GeometryTask.py
Relative to #1225 
I am not sure there is not another hidden problem.
> Fix reset using peaks

- README.rst
> Fix rst inline code

- pyFAI/test/__init__.py
- pyFAI/test/utilstest.py
> Parse test options when using run_tests function

- pyFAI/gui/tasks/GeometryTask.py
> Fix redraw of the rings

- pyFAI/opencl/azim_hist.py
> Issue when PYFAI_OPENCL="False", some Opencl stuff nevertheless loaded

- pyFAI/test/test_saxs.py
These checks are not anymore useful.
> Fix checks on deprecation warnings

- .travis.yml
- README.rst
- pyFAI/azimuthalIntegrator.py
- pyFAI/ext/splitBBox.pyx
- pyFAI/ext/splitBBoxCSR.pyx
- pyFAI/ext/splitBBoxLUT.pyx
- pyFAI/ext/splitPixelFullCSR.pyx
- pyFAI/geometry.py
- pyFAI/test/test_bug_regression.py
- pyFAI/utils/mathutil.py
> Work on missing sector when integating with disc=pi

- build-deb.sh
- pyFAI/gui/dialog/IntegrationMethodDialog.py
> splits instead of slits typo

- pyFAI/azimuthalIntegrator.py
- pyFAI/containers.py
- pyFAI/test/test_azimuthal_integrator.py
Apparently eclipse@home is more picky about trailing white spaces and CR.
@nils-blanc could you check that you can retrieve the median-filtered signal as expected ?
> 1292 separate container rebased

- pyFAI/azimuthalIntegrator.py
- pyFAI/engines/CSR_engine.py
- pyFAI/engines/preproc.py
- pyFAI/ext/preproc.pyx
- pyFAI/ext/sparse_common.pxi
- pyFAI/ext/watershed.pyx
- pyFAI/geometry.py
- pyFAI/io/__init__.py
- pyFAI/method_registry.py
- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/azim_hist.py
- pyFAI/opencl/peak_finder.py
- pyFAI/opencl/preproc.py
- pyFAI/resources/openCL/memset.cl
- pyFAI/resources/openCL/ocl_azim_CSR.cl
- pyFAI/resources/openCL/peak_finder.cl
- pyFAI/resources/openCL/preprocess.cl
- pyFAI/test/test_bug_regression.py
- pyFAI/test/test_csr.py
- pyFAI/test/test_integrate_app.py
- pyFAI/test/test_io_image.py
- pyFAI/test/test_openCL.py
- pyFAI/test/test_utils_header.py
- pyFAI/units.py
This is untested for now. to be validated
> Next generation Sigma clipping implemented in OpenCL

- pyFAI/app/__init__.py
- pyFAI/app/average.py
- pyFAI/app/benchmark.py
- pyFAI/app/calib.py
- pyFAI/app/calib2.py
- pyFAI/app/check_calib.py
- pyFAI/app/detector2nexus.py
- pyFAI/app/diff_map.py
- pyFAI/app/diff_tomo.py
- pyFAI/app/drawmask.py
- pyFAI/app/eiger_mask.py
- pyFAI/app/integrate.py
- pyFAI/app/mx_calibrate.py
- pyFAI/app/recalib.py
- pyFAI/app/saxs.py
- pyFAI/app/waxs.py
- pyFAI/engines/CSR_engine.py
- pyFAI/gui/diffmap_widget.py
> 1304 hdf5plugin

- pyFAI/app/diff_map.py
- pyFAI/gui/IntegrationDialog.py
- pyFAI/gui/dialog/GeometryDialog.py
- pyFAI/gui/model/Fit2dGeometryModel.py
Close #1306 
I don't like the conversions performed here ... but it works (I did not check everything).
> set values in FIT2D to SI to use the GUI conversion mechanism

- pyFAI/average.py
- pyFAI/diffmap.py
- pyFAI/gui/diffmap_widget.py
- pyFAI/io/image.py
- pyFAI/worker.py
Correct many glitches in the diff_map application
close #1290
> Correct diff map

- pyFAI/control_points.py
Hi,
I suggest opening the control point file within a context manager to make sure it is closed properly.
Best regards,
Bertrand
> load control points from file through a context manager

- package/debian9/rules
> use python3 also for the doc

- pyFAI/io/nexus.py
> related to #1338

- pyFAI/app/integrate.py
- pyFAI/diffmap.py
- pyFAI/gui/widgets/WorkerConfigurator.py
- pyFAI/io/__init__.py
- pyFAI/io/nexus.py
- pyFAI/test/test_integrate_app.py
- pyFAI/worker.py
> work on saving errors

- doc/source/index.rst
- doc/source/publications.rst
- doc/source/usage/cookbook/calib-gui/index.rst
Provide some video tutorial for those who don't like reading.
Armando, do you believe it is a good idea to insert videos in the documentation ?
> Provide links to the video tutorial and embed them into the web page

- CONTRIBUTING.md
> Complete contributing

- pyFAI/azimuthalIntegrator.py
Sorry for Eclipse which reformatted the code with.
> close #1347

- pyFAI/ext/_bispev.pyx
- pyFAI/ext/_blob.pyx
- pyFAI/ext/_convolution.pyx
- pyFAI/ext/_distortion.pyx
- pyFAI/ext/_geometry.pyx
- pyFAI/ext/_tree.pyx
- pyFAI/ext/bilinear.pyx
- pyFAI/ext/fastcrc.pyx
- pyFAI/ext/histogram.pyx
- pyFAI/ext/inpainting.pyx
- pyFAI/ext/invert_geometry.pyx
- pyFAI/ext/morphology.pyx
- pyFAI/ext/preproc.pyx
- pyFAI/ext/reconstruct.pyx
- pyFAI/ext/relabel.pyx
- pyFAI/ext/sparse_builder.pxd
- pyFAI/ext/sparse_builder.pxi
- pyFAI/ext/sparse_builder.pyx
- pyFAI/ext/sparse_utils.pyx
- pyFAI/ext/splitBBox.pyx
- pyFAI/ext/splitBBoxCSR.pyx
- pyFAI/ext/splitBBoxLUT.pyx
- pyFAI/ext/splitPixel.pyx
- pyFAI/ext/splitPixelFull.pyx
- pyFAI/ext/splitPixelFullCSR.pyx
- pyFAI/ext/splitPixelFullLUT.pyx
- pyFAI/ext/watershed.pyx
Close to #1349
related to https://github.com/cython/cython/issues/3560
> Fix cythonization of preproc

- setup.py
> improve generated man pages

- ci/appveyor.yml
- ci/requirements_appveyor.txt
- ci/requirements_travis.txt
- pyFAI/detectors/_common.py
Previously it was crashing at the CRC calculation as scalar values are not implementing
the buffer interface.
close #1356
> Accept scalar for flat/dark

- build-deb.sh
- pyFAI/detectors/__init__.py
- pyFAI/detectors/_esrf.py
- pyFAI/detectors/_imxpad.py
- pyFAI/detectors/_psi.py
- pyFAI/test/test_detector.py
close #1358.
For now, only a single module is supported, no information about the gap between modules are provided.
> 1358 jungfrau

- pyFAI/distortion.py
- pyFAI/worker.py
close #1361 
This code deserves more testing :(
> Simplify the calculations if the detector declares itself as distortion-free

- pyFAI/detectors/__init__.py
- pyFAI/detectors/_common.py
- pyFAI/detectors/_imxpad.py
- pyFAI/detectors/_non_flat.py
- pyFAI/detectors/_others.py
- pyFAI/detectors/_psi.py
- pyFAI/geometry.py
Minor refactoring of the detectors distribution in the files
> Define another cylindrical detector from Rigaku

- pyFAI/multi_geometry.py
- pyFAI/test/test_multi_geometry.py
> Close #1365

- pyFAI/detectors/_dectris.py
> add support for Dectris Eiger2 detectors

- pyFAI/detectors/_common.py
- pyFAI/test/test_detector.py
close #1378 
@CPrescher could you have a look if it fits your needs ?
> Remove the reference to dx and dy as they are not used.

- pyFAI/distortion.py
- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/azim_lut.py
- pyFAI/resources/openCL/ocl_azim_CSR.cl
- pyFAI/resources/openCL/ocl_azim_LUT.cl
close #1382 
Needed for ID02/Dahu
> 1382 distortion ng rebased

- pyFAI/distortion.py
- pyFAI/test/test_distortion.py
> 1385 detector distortion identity

- pyFAI/geometry.py
- pyFAI/gui/IntegrationDialog.py
- pyFAI/io/integration_config.py
- pyFAI/io/ponifile.py
- pyFAI/worker.py
> Initialize an azimuthal integrator from the JSON

- pyFAI/distortion.py
- pyFAI/worker.py
> 1394 distortion without mask rebased

- pyFAI/app/average.py
- pyFAI/average.py
Fixes a bug when using `quantiles` parameters without `quantiles` methods.
> Corrected typos in `average` files.

- pyFAI/__init__.py
- pyFAI/azimuthalIntegrator.py
> 1402 radial range

- .readthedocs.yml
> provide configuration for RTD

- pyFAI/app/sparsify.py
- pyFAI/containers.py
- pyFAI/io/sparse_frame.py
- pyFAI/opencl/azim_hist.py
- pyFAI/opencl/peak_finder.py
- pyFAI/opencl/test/__init__.py
- pyFAI/opencl/test/test_addition.py
- pyFAI/opencl/test/test_ocl_azim_csr.py
- pyFAI/opencl/test/test_ocl_azim_lut.py
- pyFAI/opencl/test/test_ocl_histo.py
- pyFAI/opencl/test/test_peak_finder.py
- pyFAI/test/test_ocl_sort.py
- pyFAI/test/test_openCL.py
- pyFAI/utils/shell.py
- setup.py
Allows the (lossy) compression of single crystal datasets.
By default, the compression ratio is about 100x,
The background is recorded assuming a polar symmetry.
The signal is sigma-clipped for 5 times (default threshold: 5 sigmas)
Then peaks are recorded (default threshold: 3 sigma).
Data are packed in HDF5 and provide a script to re-densify the data.
Close #1405
> 1405 sparsify

- pyFAI/detectors/_dectris.py
1. added eiger2 detectors: Eiger2 1M-W,Eiger2 2M-W
2. added eiger2 CdTe detectors: Eiger2 CdTe 1M-W,Eiger2 CdTe 2M-W
> added eiger2 detectors

- doc/source/conf.py
> Changing sphinx theme to sphinx_rtd_theme

- pyFAI/app/sparsify.py
Hi Thomas,
This is a fairly trivial PR which should fix the debian packaging issue.
close #1423
> Allow to request for help in `sparsify-Bragg` without opencl

- doc/source/conf.py
To avoid misunderstandings such as #1432
> Add comment for sphinx rtd theme

- package/debian10/control
- package/debian11/control
- pyFAI/app/sparsify.py
- pyFAI/io/nexus.py
- pyFAI/io/sparse_frame.py
> polish the sparsification process

- bootstrap.py
- pyFAI/calibrant.py
- pyFAI/geometryRefinement.py
- pyFAI/gui/helper/RingCalibration.py
- pyFAI/test/test_bug_regression.py
> Fixed parameters in refinement

- .github/workflows/python-package.yml
- .travis.yml
- ci/action.yml
- ci/appveyor.yml
- ci/install_pyopencl.sh
- ci/intel_opencl_icd.sh
- ci/requirements_gh.txt
- ci/requirements_travis.txt
- ci/travis.yml
- pyFAI/app/drawmask.py
- pyFAI/app/sparsify.py
- pyFAI/geometry.py
- pyFAI/io/__init__.py
- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/azim_lut.py
- pyFAI/test/test_pickle.py
The is a potential replacement for Travis-CI
> Enable Gihub action

- pyFAI/app/benchmark.py
- pyFAI/azimuthalIntegrator.py
- pyFAI/benchmark/__init__.py
- pyFAI/calibrant.py
- pyFAI/method_registry.py
- pyFAI/opencl/OCLFullSplit.py
- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/ocl_hist_pixelsplit.py
- pyFAI/opencl/peak_finder.py
- pyFAI/opencl/test/__init__.py
- pyFAI/opencl/test/test_ocl_sort.py
- pyFAI/opencl/test/test_openCL.py
- pyFAI/resources/openCL/ocl_azim_CSR.cl
- pyFAI/resources/openCL/peak_finder.cl
- pyFAI/test/test_all.py
The core idea is to probe each kernel in order to work with the recommended (optimal ?) workgroup size.
Tests have also been refactored. 
Broken configuration are also avoided.
> Dynamic worgroup

- pyFAI/distortion.py
- pyFAI/opencl/azim_csr.py
- pyFAI/resources/openCL/ocl_azim_CSR.cl
- pyFAI/test/test_distortion.py
> fix issue with distortion correction on GPU

- doc/source/usage/tutorial/Separation/Separate.ipynb
Sorry, I did not find time to review #1467 :disappointed: 
Some typos correction. The tutorial is fine though.
> Typo correction in Separate tutorials

- pyFAI/opencl/peak_finder.py
Spotted by Samuel Debionne. Thanks to him.
> Fix data type

- pyFAI/gui/widgets/WorkerConfigurator.py
- pyFAI/resources/openCL/ocl_azim_CSR.cl
Valentin, I am sure you would do this differently ...
maybe you could have an eye on it ?
close #1479
> Wire the export button

- pyFAI/ext/splitPixelFullCSR.pyx
- pyFAI/ext/splitPixelFullLUT.pyx
- pyFAI/test/test_bug_regression.py
> 1487 full csr azimuthal bug

- pyFAI/geometryRefinement.py
- pyFAI/test/test_utils.py
- pyFAI/utils/stringutil.py
- requirements.txt
this is a fairly trivial bug ... implemented regression test
> Implement a non regression test for #1490

- pyFAI/detectors/_common.py
> mask out non finite pixel coordinates

- pyFAI/detectors/_common.py
- pyFAI/geometryRefinement.py
- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/peak_finder.py
- pyFAI/resources/openCL/kahan.cl
- pyFAI/resources/openCL/ocl_azim_CSR.cl
- pyFAI/test/test_utils.py
- pyFAI/utils/stringutil.py
> azimuthal variance in OpenCL

- pyFAI/io/ponifile.py
> Distance was not read-back !

- pyFAI/ext/bilinear.pxi
- pyFAI/goniometer.py
A couple of tiny bugs spotted while analyzing ID22 goniometer data
> Gonio id22

- pyFAI/azimuthalIntegrator.py
- pyFAI/test/test_bug_regression.py
- sandbox/bad_flush.py
> Wrongly discarded CSR engine when radial_range is provided

- pyFAI/azimuthalIntegrator.py
- pyFAI/test/test_azimuthal_integrator.py
> Add missing range options to medfilt & sigma_clip

- pyFAI/gui/tasks/MaskTask.py
> Emit a signal that the mask has been loaded (hence changed)

- pyFAI/gui/helper/RingCalibration.py
- pyFAI/gui/tasks/GeometryTask.py
> 1521 fixed param

- pyFAI/azimuthalIntegrator.py
- pyFAI/engines/CSR_engine.py
- pyFAI/ext/CSR_common.pxi
- pyFAI/ext/regrid_common.pxi
- pyFAI/test/test_azimuthal_integrator.py
> Start implementing sigma-clipping in Cython

- pyFAI/io/__init__.py
- pyFAI/test/test_worker.py
- pyFAI/worker.py
> 1526 sigma clip worker

- pyFAI/geometry.py
- pyFAI/goniometer.py
correct one bug and expose many constructor parameters of MultiGeometry.
> Improve multi-geometry generation

- pyFAI/ext/_geometry.pyx
> Limit the number of threads for geometry

- pyFAI/ext/_distortion.pyx
align signatures of c-functions
> refactor distortion before moving it to regrid

- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/peak_finder.py
This is an improvement in the selection of the optimal workgroup size
> Peakfinder8

- pyFAI/goniometer.py
- pyFAI/test/test_goniometer.py
> fix a typo

- pyFAI/ext/CSR_common.pxi
- pyFAI/resources/openCL/ocl_azim_CSR.cl
Cython & OpenCL implementation are giving consistent results now
> 1564 sigma clip with azim error+cython

- pyFAI/app/sparsify.py
- pyFAI/engines/CSR_engine.py
- pyFAI/opencl/peak_finder.py
- pyFAI/resources/openCL/peak_finder.cl
- pyFAI/resources/openCL/peakfinder8.cl
*quadratically add noise
*Print informations about sparsification time (regardless to profiling)
*Peakfinder also provides the uncertainty on intensity propagated from peak integration
> set out of boind pixel invalid

- pyFAI/ext/CSR_common.pxi
- pyFAI/ext/splitBBoxCSR.pyx
- pyFAI/ext/splitPixelFullCSR.pyx
Perform 2D integration using the CsrIntegrator parent class.
Minor adaptation there
> 1444 2d inherit from csr

- pyFAI/resources/gui/calibration-experiment.ui
- pyFAI/resources/gui/calibration-geometry.ui
- pyFAI/resources/gui/calibration-peakpicking.ui
- pyFAI/resources/gui/calibration-result.ui
- pyFAI/resources/gui/integration-method.ui
- pyFAI/resources/gui/opencl-device-dialog.ui
- pyFAI/resources/gui/worker-configurator.ui
resolving tab order as described in issue #1577
> fixed tab order to be from left to right and from top to bottom

- pyFAI/gui/peak_picker.py
> fix issue on calib2

- package/debian11/rules
build doc/man only when needed
> Parallel debian

- pyFAI/ext/splitPixelFullCSR.pyx
- pyFAI/ext/splitPixelFullLUT.pyx
- pyFAI/ext/splitpixel_common.pyx
This PR cleans up the code by factorizing the generation of the LUT/CSR for all 2D intergrators doing full-pixel-plitting
> Factorize LUT creation with common parent class

- pyFAI/azimuthalIntegrator.py
- pyFAI/ext/regrid_common.pxi
- pyFAI/ext/splitBBoxCSR.pyx
- pyFAI/ext/splitBBoxLUT.pyx
- pyFAI/ext/splitPixel.pyx
- pyFAI/ext/splitPixelFullCSR.pyx
- pyFAI/ext/splitPixelFullLUT.pyx
- pyFAI/ext/splitpixel_common.pxd
- pyFAI/ext/splitpixel_common.pyx
- pyFAI/gui/peak_picker.py
- pyFAI/test/test_flat.py
- pyFAI/test/test_sparse.py
- pyFAI/test/test_split_pixel.py
Global clean up of all Cython code
> Fix fullsplit tests

- pyFAI/test/test_integrate_app.py
- setup.py
Restore the `python setup.py testimages` command
> Testimages

- pyFAI/ext/histogram.pyx
- pyFAI/ext/regrid_common.pxi
- pyFAI/ext/setup.py
- pyFAI/ext/splitBBox.pyx
- pyFAI/ext/splitBBoxCSR.pyx
- pyFAI/ext/splitBBoxLUT.pyx
- pyFAI/ext/splitBBox_common.pyx
- pyFAI/ext/splitPixelFullCSR.pyx
- pyFAI/ext/splitPixelFullLUT.pyx
- pyFAI/ext/splitpixel_common.pyx
- pyFAI/gui/cli_calibration.py
- pyFAI/test/test_bug_regression.py
- pyFAI/test/test_sparse.py
> Refactor bounding-box pixel splitting

- pyFAI/ext/CSR_common.pxi
- pyFAI/ext/LUT_common.pxi
- pyFAI/ext/bilinear.pxi
- pyFAI/ext/sparse_builder.pxi
- pyFAI/ext/splitBBox.pyx
- pyFAI/ext/splitBBox_common.pyx
- pyFAI/ext/splitpixel_common.pyx
- pyFAI/test/test_integrate_app.py
- pyFAI/test/test_sparse.py
- pyFAI/test/test_split_pixel.py
> Fix consistancy of `bbox` with `histogram` vs `LUT` vs `CSR` and associated tests

- pyFAI/app/integrate.py
- pyFAI/azimuthalIntegrator.py
- pyFAI/benchmark/__init__.py
- pyFAI/engines/histogram_engine.py
- pyFAI/ext/histogram.pyx
- pyFAI/io/__init__.py
- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/azim_lut.py
- pyFAI/opencl/test/test_openCL.py
- pyFAI/test/test_bug_regression.py
- pyFAI/test/test_csr.py
- pyFAI/test/test_integrate.py
- pyFAI/test/test_sparse.py
* fix tests for 2D integration
* Make 2D integration use new generation algorithm
* use integrate2d_ng in pyFAI-integrate
> 1611 integrate

- pyFAI/directories.py
- pyFAI/geometryRefinement.py
- pyFAI/opencl/test/test_ocl_sort.py
- pyFAI/test/__init__.py
- pyFAI/test/test_azimuthal_integrator.py
- pyFAI/test/test_detector.py
- pyFAI/test/test_integrate.py
- pyFAI/test/utilstest.py
- run_tests.py
> clean up some tests and empty tmp directory at exit

- pyFAI/azimuthalIntegrator.py
- pyFAI/directories.py
- pyFAI/engines/CSR_engine.py
- pyFAI/geometryRefinement.py
- pyFAI/load_integrators.py
- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/azim_hist.py
- pyFAI/opencl/azim_lut.py
- pyFAI/opencl/test/test_ocl_histo.py
- pyFAI/opencl/test/test_ocl_sort.py
- pyFAI/test/__init__.py
- pyFAI/test/test_azimuthal_integrator.py
- pyFAI/test/test_detector.py
- pyFAI/test/test_integrate.py
- pyFAI/test/utilstest.py
- run_tests.py
> 1444 python csr integrator 2d

- pyFAI/app/benchmark.py
- pyFAI/benchmark/__init__.py
> Improve the benchmark with additionnal images and update graph

- pyFAI/diffmap.py
- pyFAI/gui/diffmap_widget.py
- pyFAI/worker.py
Improvement in diffmap GUI tool:
* Allow 2d integration (caking)
* Allow error propagation
> Diffmap cake

- pyFAI/detectors/__init__.py
- pyFAI/detectors/_hexagonal.py
- pyFAI/test/test_detector.py
- pyFAI/test/test_integrate_app.py
> Support detectors with hexagonal pixel pattern

- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/azim_hist.py
- pyFAI/opencl/azim_lut.py
- pyFAI/opencl/peak_finder.py
- pyFAI/opencl/preproc.py
> Extended OpenCL mapping to numpy c-datatypes

- pyFAI/detectors/__init__.py
- pyFAI/detectors/_xspectrum.py
> Support Lambda detectors

- pyFAI/detectors/_dectris.py
> 1660 eiger250k

- pyFAI/gui/jupyter/_plot.py
@elena-pascal
Thanks for the patch
> Patch from elena

- pyFAI/app/integrate.py
- pyFAI/gui/IntegrationDialog.py
- pyFAI/gui/widgets/WorkerConfigurator.py
- pyFAI/test/test_worker.py
- pyFAI/worker.py
@vallsv does this patch sound to you ?
close #1670
> Explicit error message when unconsistant configuration, typically number of points not provided in GUI

- doc/source/man/MX-calibrate.rst
- doc/source/usage/tutorial/Goniometer/index.rst
- pyFAI/gui/cli_calibration.py
- pyFAI/gui/jupyter/calib.py
- pyFAI/gui/mpl_calib.py
Fix minor bugs found ...
Also, provide a Jupyter based MX-calibrate tool
> Calibration of MX-translation stage

- pyFAI/azimuthalIntegrator.py
> Fix regression with context retrieval

- pyFAI/gui/widgets/QuantityEdit.py
prevents data from being elided
Alternative to #1682
> Ensures the LineEdit widget is large enough to host all digits

- pyFAI/app/peakfinder.py
- pyFAI/ext/bilinear.pxi
- pyFAI/geometry.py
- pyFAI/io/__init__.py
- pyFAI/io/spots.py
- pyFAI/test/test_detector.py
- pyFAI/test/test_export.py
- pyFAI/test/test_io.py
- pyFAI/test/test_polarization.py
- pyFAI/third_party/_local/transformations.py
close #1638
* export of the geometry of pyFAI to the one of defined in CXI
* import the CXI geometry
* minor improvement in the calculation of polarization (using numexpr)
* todo export peak position in the proper format
> Export peakfiner data to CXI format

- pyFAI/gui/utils/unitutils.py
- pyFAI/multi_geometry.py
> Use collection.abc

- pyFAI/ext/invert_geometry.pyx
- pyFAI/test/test_invert_geometry.py
@CPrescher does this fit your needs ?
> inver geometry on several points

- plugins/Lima/AzimuthalIntegration.py
- plugins/Lima/limaFAI.py
- pyFAI/gui/widgets/WorkerConfigurator.py
- pyFAI/io/__init__.py
- pyFAI/resources/gui/worker-configurator.ui
- pyFAI/test/test_worker.py
- pyFAI/worker.py
- sandbox/processor.py
> replace do_poisson (bool) with error_model (str)

- setup.py
Incompatibility with default arguments in namedtuple.
close #1721
> Drop Python3.6

- bootstrap.py
- doc/source/statistics.rst
- pyFAI/azimuthalIntegrator.py
- pyFAI/containers.py
- pyFAI/io/nexus.py
- pyFAI/io/ponifile.py
- pyFAI/test/test_io.py
- sandbox/nexus_monopd.py
- version.py
> Write Nexus file following NXmonopd application definition

- pyFAI/geometry/__init__.py
- pyFAI/geometry/core.py
- pyFAI/multi_geometry.py
- pyFAI/setup.py
- version.py
Separate geometry into a separated sub-module
> Refactor geometry

- pyFAI/geometry/core.py
> Typo in load from poni

- pyFAI/opencl/__init__.py
- pyproject.toml
- requirements.txt
- setup.py
Thanks Thomas for reporting it.
> Make silx 1.1 a dependency

- pyFAI/ext/CSC_common.pxi
- pyFAI/ext/CSR_common.pxi
- pyFAI/ext/LUT_common.pxi
- pyFAI/opencl/azim_hist.py
- pyFAI/test/test_azimuthal_integrator.py
- version.py
> 1760 public empty

- pyFAI/opencl/azim_csr.py
- pyFAI/opencl/peak_finder.py
- pyFAI/resources/openCL/ocl_azim_CSR.cl
- pyFAI/resources/openCL/sparsify.cl
> Make opencl workgroups tunable without recompiling

- doc/source/conventions.rst
- doc/source/img/pixel_coordinates.svg
- doc/source/index.rst
Hi,
as discussed I prepared a pull-request for the new documentation page. Unfortunately I don't know how to test the documentation !
Hopefully it is simple enough to avoid doing too many mistakes !
thanks !
marco
> untested "conventions" documentation page

- pyFAI/ext/splitBBox.pyx
> typo in dict method name

- pyFAI/detectors/_xspectrum.py
> Tune lambda detector sizes + gaps

- pyFAI/azimuthalIntegrator.py
> take the position of the discontinuity in consideration

- bootstrap.py
- pyFAI/calibrant.py
- pyFAI/control_points.py
- pyFAI/geometryRefinement.py
- pyFAI/goniometer.py
- pyFAI/gui/peak_picker.py
- pyFAI/massif.py
- pyFAI/multi_geometry.py
- pyFAI/test/test_bug_regression.py
- pyFAI/test/test_goniometer.py
- pyFAI/test/test_utils.py
- pyFAI/utils/meson.build
- pyFAI/utils/multiprocessing.py
- version.py
> 1811 multigeometry

- pyFAI/app/sparsify.py
> correct test

- pyFAI/gui/model/ImageModel.py
> Handle the case of boolean images

- pyFAI/azimuthalIntegrator.py
- pyFAI/test/test_worker.py
> Enable sigma_clip_legacy to be used within a worker

- pyFAI/goniometer.py
related to https://gitlab.esrf.fr/workflow/ewoksapps/ewoksxrpd/-/issues/22
> retrieve wavelength only if defined

- pyFAI/app/diff_map.py
- pyFAI/diffmap.py
- pyFAI/worker.py
- version.py
> Make diffmap work without GUI (just a JSON config file)

- pyFAI/detectors/_common.py
- pyFAI/detectors/_dectris.py
- pyFAI/goniometer.py
- pyFAI/gui/peak_picker.py
- pyFAI/massif.py
- pyFAI/test/test_detector.py
- pyFAI/test/utilstest.py
- run_tests.py
close #1860 
@CPrescher  could you have a look if it fits your needs ?
> 1860 rework massif

- pyFAI/azimuthalIntegrator.py
Ideally one should  do a non regression test.
close #1864
> performance of sigma-clip when enforcing range

- doc/source/api/engines/index.rst
- pyFAI/azimuthalIntegrator.py
- pyFAI/engines/CSC_engine.py
- pyFAI/engines/CSR_engine.py
- pyFAI/engines/meson.build
- pyFAI/ext/CSC_common.pxi
- pyFAI/load_integrators.py
> 1846 csc python

- doc/source/changelog.rst
- pyFAI/ext/splitBBoxCSC.pyx
- pyFAI/worker.py
> Improve resilience of CSC

- pyFAI/azimuthalIntegrator.py
- pyFAI/io/__init__.py
- pyFAI/io/ponifile.py
> 1884 io headers

- bootstrap.py
- build-deb.sh
- meson.build
- package/debian12/control
- version.py
small improvements ported from fabio
> Debian12 again

- pyFAI/gui/model/ListModel.py
- pyFAI/gui/tasks/PeakPickingTask.py
Some small changes to make pyfai-calib2 compatible with PySide6.
Fix for issue  #1918
> Make pyfai-calib2 pyside6 compatible

- pyFAI/ext/splitBBox_common.pyx
- pyFAI/ext/splitpixel_common.pyx
This used to be the root of inconsistencies when running tests
Close #1915
> Fix unitialized scalars

- pyFAI/detectors/_common.py
the test was the other way around ... gave only none-sense results.
Decrease also the verbosity level
> Correct dynamic mask

- pyFAI/app/calib2.py
- pyFAI/app/eiger_mask.py
- pyFAI/gui/IntegrationDialog.py
- pyFAI/gui/dialog/DetectorSelectorDialog.py
- pyFAI/gui/dialog/OpenClDeviceDialog.py
- pyFAI/gui/helper/RingExtractor.py
- pyFAI/gui/model/DataModelAdaptor.py
- pyFAI/gui/model/PeakModel.py
- pyFAI/gui/tasks/ExperimentTask.py
- pyFAI/gui/tasks/GeometryTask.py
- pyFAI/gui/tasks/IntegrationTask.py
- pyFAI/gui/tasks/PeakPickingTask.py
- pyFAI/gui/utils/unitutils.py
- pyFAI/gui/widgets/CalibrantSelector.py
- pyFAI/gui/widgets/FitParamView.py
- pyFAI/gui/widgets/WorkerConfigurator.py
> fix English spelling.

- pyFAI/opencl/test/test_addition.py
- pyFAI/opencl/test/test_openCL.py
- pyFAI/test/test_average.py
- pyFAI/test/test_azimuthal_integrator.py
- pyFAI/test/test_bayes.py
- pyFAI/test/test_bilinear.py
- pyFAI/test/test_bug_regression.py
- pyFAI/test/test_error_model.py
- pyFAI/test/test_flat.py
- pyFAI/test/test_geometry.py
- pyFAI/test/test_goniometer.py
- pyFAI/test/test_histogram.py
- pyFAI/test/test_io.py
- pyFAI/test/test_massif.py
- pyFAI/test/test_pickle.py
- pyFAI/test/test_preproc.py
- pyFAI/test/test_split_pixel.py
- pyFAI/test/test_utils_mathutil.py
- pyFAI/test/test_worker.py
- pyFAI/test/utilstest.py
> Centralized control on the seeding of RNG

- doc/source/changelog.rst
- pyFAI/app/calib2.py
> expose range in calib2 application

- pyFAI/gui/tasks/IntegrationTask.py
> Handle properly units after 2D integration

- pyFAI/test/meson.build
- pyFAI/test/test_all.py
- pyFAI/test/test_geometry.py
- pyFAI/test/test_units.py
- pyFAI/units.py
- version.py
Nice to have it to validate #1970
> Ensure consistency of numpy and numexpr evaluation of formula.

- pyFAI/load_integrators.py
- pyFAI/test/test_bug_regression.py
> Expose method ("full", "csc", "python")

- src/pyFAI/resources/openCL/preprocess.cl
There are a couple of compilation errors which remain but those are linked to specific types of atomic operation not available (work-around are available and implemented).
close #1977
> fix compilation warning

- src/pyFAI/io/integration_config.py
- src/pyFAI/test/test_worker.py
- src/pyFAI/worker.py
> serialize worker config and deserialize as azimuthal integrator

- src/pyFAI/detectors/_common.py
- src/pyFAI/test/test_detector.py
> warn on  unexpected parameters in constructor

- bootstrap.py
- build-deb.sh
- doc/source/conventions.rst
- run_tests.py
- src/pyFAI/_version.py
- src/pyFAI/detectors/_common.py
- src/pyFAI/detectors/_dectris.py
- src/pyFAI/detectors/_imxpad.py
- src/pyFAI/detectors/_non_flat.py
- src/pyFAI/detectors/_psi.py
- src/pyFAI/detectors/orientation.py
- src/pyFAI/ext/_geometry.pyx
- src/pyFAI/geometry/core.py
- src/pyFAI/io/ponifile.py
- src/pyFAI/test/test_detector.py
- src/pyFAI/test/test_geometry.py
Check direction of chi is correct:
> 2003 orientation

- src/pyFAI/detectors/_common.py
- src/pyFAI/detectors/_imxpad.py
- src/pyFAI/geometry/core.py
- src/pyFAI/test/test_detector.py
- src/pyFAI/test/test_geometry.py
> Orientation ... still bugs in some calculations

- src/pyFAI/geometry/core.py
- src/pyFAI/test/test_geometry.py
Was already good in the `deltaChi()` method.
close #2024
> Fix the 2-pi discontinuity when using `delta_array` with chi-space 

- doc/source/changelog.rst
- src/pyFAI/ext/histogram.pyx
- src/pyFAI/io/ponifile.py
- src/pyFAI/test/test_io.py
> support pathlib.Path

- doc/source/changelog.rst
- src/pyFAI/azimuthalIntegrator.py
- src/pyFAI/io/__init__.py
- src/pyFAI/io/meson.build
- src/pyFAI/io/xrdml.py
- src/pyFAI/test/test_io.py
close #1648 
File can be opened with MAUD (lost uncertainties)
> Support Xrdml

- doc/source/changelog.rst
- src/pyFAI/detectors/_dectris.py
Add return statement in the __repr__ method of class Pilatus4M
> Pilatus4M __repr__

- src/pyFAI/gui/tasks/ExperimentTask.py
- src/pyFAI/gui/tasks/GeometryTask.py
- src/pyFAI/gui/tasks/IntegrationTask.py
- src/pyFAI/gui/tasks/MaskTask.py
- src/pyFAI/gui/tasks/PeakPickingTask.py
> address deprecation warning

- src/pyFAI/gui/cli_calibration.py
would make a new tutorial on flatfield calculation simpler ...
> improvements for the calibration from the notebook

- src/pyFAI/multi_geometry.py
close #2051
After ~10 cycles, the memory consumption converges towards 26-27GB and stays stable
> reset thread-pool

- src/pyFAI/ext/CSR_common.pxi
- src/pyFAI/ext/LUT_common.pxi
- src/pyFAI/test/test_bug_regression.py
Align LUT on CSR for uncertainties management
close #2053
> 2053 lut uncertainties

- doc/source/changelog.rst
- src/pyFAI/gui/model/ExperimentSettingsModel.py
> Use the dynamic mask in the calibration GUI

- src/pyFAI/azimuthalIntegrator.py
- src/pyFAI/ext/CSC_common.pxi
- src/pyFAI/ext/CSR_common.pxi
- src/pyFAI/ext/histogram.pyx
- src/pyFAI/ext/regrid_common.pxi
- src/pyFAI/ext/splitBBox.pyx
- src/pyFAI/ext/splitBBoxCSC.pyx
- src/pyFAI/ext/splitPixel.pyx
- src/pyFAI/test/meson.build
- src/pyFAI/test/test_all.py
- src/pyFAI/test/test_bug_regression.py
- src/pyFAI/test/test_flat.py
- src/pyFAI/test/test_uncertainties.py
> Extend azimuthal uncertainties to all cython integrators (in 1D for now)

- src/pyFAI/diffmap.py
- src/pyFAI/test/test_bug_regression.py
> Fix diff_tomo tool

- ci/requirements_appveyor.txt
- ci/requirements_gh.txt
- ci/requirements_rtd.txt
- ci/requirements_travis.txt
- pyproject.toml
- requirements.txt
- src/pyFAI/resources/__init__.py
> fix pkg resources deprecation

- src/pyFAI/test/test_worker.py
- src/pyFAI/worker.py
One pitfall: if a piece of code is setting this shape !
close #2084
> make worker.shape a property using the detector from the azimuthal integrator

- src/pyFAI/geometryRefinement.py
> Refine wavelength

- src/pyFAI/app/calib2.py
- src/pyFAI/gui/helper/RingCalibration.py
- src/pyFAI/gui/widgets/MethodLabel.py
> Display method in the proper order

- src/pyFAI/goniometer.py
Thanks @woutdenolf  for the report.
close #2115
> close #2115

- src/pyFAI/app/diff_tomo.py
- src/pyFAI/diffmap.py
- src/pyFAI/gui/diffmap_widget.py
Now, Diffmap is instantiated in DiffMapWidget in a more general way.
To do that, I had to unify the name of the variables: from "fast_motor_points" to "nbpt_fast", and from "slow_motor_points" to "nbpt_slow"
Also, took the chance to refactor "npt_rad" and "npt_azim" to "nbpt_rad" and "nbpt_azim", respectively, which is the worker nomenclature
> 2113 diffmap variables

- src/pyFAI/diffmap.py
- src/pyFAI/gui/diffmap_widget.py
Something like this? In set_config, the keys of the incoming dictionary are updated with deprecation warning
> deprecation warning in set_config

- src/pyFAI/test/test_blob_detection.py
> Fix test for numpy2

- src/pyFAI/opencl/OCLFullSplit.py
- src/pyFAI/opencl/azim_csr.py
- src/pyFAI/opencl/azim_hist.py
- src/pyFAI/opencl/azim_lut.py
- src/pyFAI/opencl/ocl_hist_pixelsplit.py
- src/pyFAI/opencl/peak_finder.py
- src/pyFAI/opencl/sort.py
- src/pyFAI/test/test_distortion.py
- src/pyFAI/test/test_geometry.py
Remains the code related to numpy.array( copy=False)
related to #2099
> Fix some tests related to numpy2

- src/pyFAI/detectors/_common.py
- src/pyFAI/test/test_detector.py
> Rebin the mask as needed

- src/pyFAI/azimuthalIntegrator.py
- src/pyFAI/diffmap.py
- src/pyFAI/io/integration_config.py
- src/pyFAI/load_integrators.py
- src/pyFAI/opencl/__init__.py
- src/pyFAI/test/test_integrate_config.py
- version.py
> parser should not mangle method (too much)

- src/pyFAI/benchmark/__init__.py
* Store CPU + GPU infromation into JSON file
* simplify / update the code
> Improve benchmarks:

- README.rst
- src/pyFAI/test/test_geometry.py
- src/pyFAI/test/test_utils_mathutil.py
- src/pyFAI/utils/mathutil.py
> Address numerical precision issue on macos/arm64

- .github/workflows/release.yml
- README.rst
- bootstrap.py
- meson.build
- meson.options
- pyproject.toml
- src/pyFAI/ext/meson.build
> Options to force-disable openmp

- .github/workflows/release.yml
- meson.build
> Disable openmp via environment variable

- src/pyFAI/gui/mpl_calib.py
https://matplotlib.org/3.9.0/api/prev_api_changes/api_changes_3.9.0.html#top-level-cmap-registration-and-access-functions-in-mpl-cm
> fix code for latest version of matplotlib (3.9)

- src/pyFAI/test/test_ring_extraction.py
> Fix issue related to threading used in ring extractor

- src/pyFAI/resources/openCL/separate.cl
> Wrongly assigned empty ensemble in medfilt after sort ... it was just very small

- src/pyFAI/detectors/_common.py
- src/pyFAI/gui/CalibrationWindow.py
- src/pyFAI/gui/model/MarkerModel.py
- src/pyFAI/gui/tasks/ExperimentTask.py
- src/pyFAI/test/test_detector.py
One for the image and another for the detector.
close #2177
> Provide two distinct origins when the detector is flipped

- src/pyFAI/calibrant.py
Can be useful ... 
One issue: lacks test coverage.
> Store extinction rules for certain space groups.

- src/pyFAI/azimuthalIntegrator.py
- src/pyFAI/containers.py
- src/pyFAI/ext/CSR_common.pxi
> Implement sigma-clip with hybrid error-model using Cython

- src/pyFAI/ext/splitBBox.pyx
- src/pyFAI/ext/splitPixel.pyx
- src/pyFAI/gui/widgets/CalibrantSelector2.py
- src/pyFAI/opencl/azim_lut.py
close #2208 
* bbox-histogram-cython
* full-histogram-cython
> wire absorption into various engines

- src/pyFAI/detectors/_common.py
config should contain the kwargs of the constructor
> export orientation also for nexus detectors

- src/pyFAI/diffmap.py
- src/pyFAI/gui/diffmap_widget.py
- src/pyFAI/resources/gui/diffmap.ui
> [diffmap] Update GUI to accomodate motor position widget

- src/pyFAI/diffmap.py
- src/pyFAI/gui/pilx/MainWindow.py
> pilx: Display frame index as plot title

- src/pyFAI/detectors/_psi.py
> Declare the Jungfrau 1M detector of ID09

- src/pyFAI/io/integration_config.py
- src/pyFAI/test/test_worker.py
- version.py
> Generic detector in worker

- src/pyFAI/worker.py
> clean-up worker module

- src/pyFAI/app/pilx.py
- src/pyFAI/gui/pilx/MainWindow.py
- src/pyFAI/gui/pilx/point.py
- src/pyFAI/gui/pilx/widgets/MapPlotWidget.py
Changes to handle generic locations of raw data and nxprocess with integrated results. To be implemented in an ewoks task for cultural heritage BAG experiment.
> [pilx] fix some bugs and generic input data and nxprocess

- src/pyFAI/gui/widgets/WorkerConfigurator.py
- src/pyFAI/resources/gui/worker-configurator.ui
- src/pyFAI/worker.py
> [pyFAI-integrate] 2229: sigmaclip in pyFAIintegrate

- src/pyFAI/engines/CSC_engine.py
- src/pyFAI/engines/CSR_engine.py
- src/pyFAI/ext/CSR_common.pxi
- src/pyFAI/opencl/azim_csr.py
- src/pyFAI/test/test_csr.py
- src/pyFAI/test/test_histogram.py
So that it matches all other integrators
close #2255
> Transpose output matrices for CSR and CSC in Python

- src/pyFAI/detectors/_common.py
- src/pyFAI/geometry/crystfel.py
- src/pyFAI/geometry/meson.build
- src/pyFAI/test/test_geometry.py
misses some regression tests ...
Close #2253
> Generic CrystFEL geometry file parser

- src/pyFAI/multi_geometry.py
- src/pyFAI/test/test_multi_geometry.py
> Compatibility between GI and MultiGeometry

- src/pyFAI/resources/openCL/peakfinder.cl
> Discard peaks with masked pixels

- src/pyFAI/diffmap.py
> Access HDF5 file after closing

- src/pyFAI/app/calib2.py
> Setting the polarization factor

- src/pyFAI/method_registry.py
- src/pyFAI/test/test_method_registry.py
> relax condition for equality for integration methods

- src/pyFAI/opencl/preproc.py
> fix SyntaxWarning

- src/pyFAI/test/test_method_registry.py
Simple patch to make the tests less noisy
> Fix deprecation warning

- src/pyFAI/engines/CSR_engine.py
- src/pyFAI/test/meson.build
- src/pyFAI/test/test_all.py
- src/pyFAI/test/test_medfilt_engine.py
> Python implementation of medfilt_ng

- src/pyFAI/diffmap.py
> Correct missing method: `setup_ai`

- doc/source/publications.rst
- src/pyFAI/diffmap.py
- src/pyFAI/io/image.py
To be checked on ID27's setup
close #2361
> Handle diffmap mask as URL

- src/pyFAI/integrator/fiber.py
repr of the Fiber with the additional parameters
> fiber repr

- src/pyFAI/diffmap.py
> use `unit.space` in  diffmap.py

- src/pyFAI/detectors/_common.py
- src/pyFAI/test/test_worker.py
Json-deserialized objects are lists, not tuples...
> Ensure max_shape is a tuple (not a list)

- src/pyFAI/gui/tasks/IntegrationTask.py
> Simplify by using dataclasses in calib2

- src/pyFAI/gui/pilx/utils.py
> pilx binning

- src/pyFAI/io/nexus.py
> Ensure the 2 opened file in the Nexus class are actually closed when the object is deleted

- src/pyFAI/benchmark/__init__.py
> dynamic range in benchmark

- src/pyFAI/worker.py
So we can use `IntegrationMethod` also as input
> [Worker] parse_integration_method

- src/pyFAI/gui/helper/SynchronizeRawView.py
- src/pyFAI/gui/model/ListModel.py
> Pyside6 compatibility of calib2

- src/pyFAI/diffmap.py
- src/pyFAI/gui/diffmap_widget.py
- src/pyFAI/io/ponifile.py
- src/pyFAI/resources/gui/diffmap.ui
- src/pyFAI/resources/gui/worker-configurator.ui
> Implement zig-zag scan

- src/pyFAI/diffmap.py
- src/pyFAI/gui/diffmap_widget.py
- src/pyFAI/io/diffmap_config.py
- src/pyFAI/test/test_io_diffmap_config.py
close #2504
Checked by running diffmap several times with different configs
> Non regression test for ListDataSet

- src/pyFAI/integrator/azimuthal.py
> docstring for medfilt_ng

- doc/source/usage/tutorial/Performances-2D.ipynb
- doc/source/usage/tutorial/index.rst
Linked to
https://github.com/silx-kit/pyFAI/discussions/2516
> Doc perf2d

- src/pyFAI/diffmap.py
- src/pyFAI/gui/diffmap_widget.py
- src/pyFAI/io/diffmap_config.py
- src/pyFAI/io/integration_config.py
- src/pyFAI/io/ponifile.py
- src/pyFAI/test/test_integrate_config.py
- src/pyFAI/test/test_io_diffmap_config.py
> Use DiffMapConfig dataclass

- src/pyFAI/diffmap.py
- src/pyFAI/gui/diffmap_widget.py
- src/pyFAI/gui/matplotlib.py
- src/pyFAI/gui/pilx/MainWindow.py
- src/pyFAI/io/diffmap_config.py
- src/pyFAI/test/test_bug_regression.py
- src/pyFAI/test/test_io_diffmap_config.py
> Implement the storage of the `map_ptr` in 

- src/pyFAI/diffmap.py
- src/pyFAI/io/__init__.py
- src/pyFAI/io/nexus.py
- src/pyFAI/io/sparse_frame.py
- src/pyFAI/io/spots.py
The rational is to avoid breaking display when using external links
> use relative path for default NeXus attribute

- src/pyFAI/gui/cli_calibration.py
Closes #2540
- Changed all initializations of `self.fixed` from a list to a `FixedParameters` set in `cli_calibration.py`.
- Ensured compatibility with existing code by using `FixedParameters(["wavelength", "rot3"])` where needed.
- No errors found after the change.
- Provides compatibility with existing functionality while transitioning `calibration.fixed` to a `set`, as required for geometry refinement and parameter fixing.
- Prepares the codebase for future type safety and efficient set operations.
- Run calibration workflows.
- Confirm that parameter fixing/unfixing behaves as expected.
- No functional changes should be observed by end users.
> Fixed issues 2540

- doc/source/changelog.rst
- src/pyFAI/app/pilx.py
- src/pyFAI/gui/pilx/HorizontalRangeROI.py
- src/pyFAI/gui/pilx/MainWindow.py
- src/pyFAI/gui/pilx/point.py
- src/pyFAI/gui/pilx/utils.py
Related to 
https://github.com/kif/dahu/issues/91
close #2513
> Make `pilx` compatible with mesh-scan files produced by dahu on bm29

- src/pyFAI/containers.py
- src/pyFAI/gui/jupyter/_plot.py
- src/pyFAI/integrator/fiber.py
- src/pyFAI/test/test_fiber_integrator.py
> Grazing incidence improvements

- doc/source/conf.py
- version.py
> use pathlib.Path in sphinx configuration

- doc/source/changelog.rst
- src/pyFAI/containers.py
- src/pyFAI/crystallography/calibrant.py
- src/pyFAI/crystallography/cell.py
- src/pyFAI/crystallography/meson.build
- src/pyFAI/crystallography/resolution.py
- src/pyFAI/io/calibrant_config.py
- src/pyFAI/test/meson.build
- src/pyFAI/test/test_all.py
- src/pyFAI/test/test_calibrant.py
- src/pyFAI/test/test_crystallography.py
- src/pyFAI/test/test_fiber_integrator.py
Merge after #2570 
close #2562
> calibrant use dataclass for IO

- src/pyFAI/calibrant.py
- src/pyFAI/control_points.py
> modernize the style of the properties

- src/pyFAI/integrator/azimuthal.py
- src/pyFAI/resources/openCL/medfilt.cl
- version.py
While debugging why the median filter kernel was not working with PoCL
> Opencl polishing

- src/pyFAI/integrator/azimuthal.py
> handle semi-defined ranges

- doc/source/changelog.rst
- src/pyFAI/containers.py
- src/pyFAI/geometry/core.py
- src/pyFAI/goniometer.py
- src/pyFAI/gui/cli_calibration.py
- src/pyFAI/gui/helper/MarkerManager.py
- src/pyFAI/gui/helper/RingCalibration.py
- src/pyFAI/gui/helper/RingExtractor.py
- src/pyFAI/gui/tasks/IntegrationTask.py
- src/pyFAI/integrator/azimuthal.py
- src/pyFAI/integrator/common.py
- src/pyFAI/opencl/test/test_ocl_histo.py
- src/pyFAI/ring_extraction.py
- src/pyFAI/test/test_ring_extraction.py
- src/pyFAI/test/test_split_pixel.py
- src/pyFAI/test/test_units.py
- src/pyFAI/test/test_utils.py
- src/pyFAI/units.py
- src/pyFAI/utils/__init__.py
- version.py
The later is using the numpy|numexpr path and is proven to be more consitent than the cython path. The later is kept for geometry refinement purposes mostly.
> replace `chiArray` with `center_array(CHI_RAD)`

- src/pyFAI/crystallography/calibrant.py
- src/pyFAI/geometry/core.py
- src/pyFAI/geometryRefinement.py
- src/pyFAI/gui/helper/RingCalibration.py
- src/pyFAI/gui/tasks/IntegrationTask.py
- src/pyFAI/gui/widgets/CalibrantPreview.py
- src/pyFAI/units.py
- src/pyFAI/utils/__init__.py
This is a consequence of the API change last summer
> fix some deprecation warning in pyFAI-calib2
